//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by CAPDLL.RC
//
#define IDB_CALIB                       3
#define IDD_CALIBKEKKA                  103
#define IDC_COLOR                       124
#define IDC_IN1                         1000
#define IDC_IN2                         1001
#define IDC_IN3                         1002
#define IDC_IN4                         1003
#define IDC_FRAME                       1004
#define IDC_OUT                         1005
#define IDC_IN                          1006
#define IDC_START                       1007
#define IDC_P1                          1008
#define IDC_P2                          1009
#define IDC_P3                          1010
#define IDC_P4                          1011
#define IDC_P5                          1012
#define IDC_P6                          1013
#define IDC_P7                          1014
#define IDC_P8                          1015
#define IDC_P9                          1016
#define IDC_P10                         1017
#define IDC_SEC                         1018
#define IDC_STATIC1                     1019
#define IDC_STATIC2                     1021
#define IDC_STATIC3                     1022
#define IDC_STATIC4                     1023
#define IDC_STATIC5                     1024
#define IDC_STATIC6                     1025
#define IDC_STATIC7                     1026
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         102
#define _APS_NEXT_CONTROL_VALUE         1024
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
