/************************************************************************
 *									*
 *		ＯＳ／２　オンラインユーザサポートシステム		*
 *			ＰＣ－ＮＥＴ／２				*
 *									*
 *		名称		: 共通インクルードファイル		*
 *		ファイル名	: pcnet.h				*
 *		作成者		: s.aizawa				*
 *									*
 ************************************************************************/

#define INCL_BASE
#define INCL_PM
#include <os2.h>
#include <stdio.h>
#include "isam.h"
#include "define.h"
#include "struct.h"
#include "extern.h"
#include "dlg.h"
