/*	respons code	*/

#define	R_NORMAL	0		/* normal end		*/
#define	R_CMDERR	0x010		/* command error	*/
#define	R_PRMERR	0x020		/* parameter error	*/

#define	R_CCSTO		0x110		/* CS on time out (conxxxt)	*/
#define	R_CIND		0x120		/* receive indication		*/
#define	R_CCOFTO	0x130		/* CS off time out		*/
#define	R_CDRTO		0x140		/* DR time out (conxxxt)	*/

#define	R_AUTOERR	0x150		/* AUTO	COME REQUEST ERROR	*/
