//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MMA_G.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_INDICATOR_GUIDE              104
#define IDR_MAINFRAME                   128
#define IDR_MMA_GTYPE                   129
#define IDB_IMAGE_LIST                  130
#define IDD_GRAPH_BAR_ACCL              131
#define IDR_GRAPHFRAME                  132
#define IDC_HANDCLOSE                   133
#define IDD_FFT_SPECTRUM                134
#define IDD_FFT_OCTAVE                  135
#define IDD_FFT_SPECTROGRAM             136
#define IDD_DIGITAL_DATA                138
#define IDD_PROGRESS_BAR                139
#define IDD_TIME_RANGE                  140
#define IDD_CONV_DATA                   141
#define IDD_CONV_CSV                    142
#define IDI_SPECTRUM                    151
#define IDI_OCTAVE                      152
#define IDI_SPECTROGRAM                 153
#define IDD_GRAPH_DIGITAL_DATA          156
#define IDD_GRAPH_DIGITAL_DATA_ROWCOL   157
#define IDD_GRAPH_TITLE                 158
#define IDD_SELECT_RSU                  159
#define IDD_SELECT_START_TIME           162
#define IDD_CHANGE_INFO                 163
#define IDD_GRAPH_BAR_TEMP              164
#define IDD_ANALYZE_RANGE               165
#define IDD_CONV_DATA_MME               166
#define IDD_CHANGE_INFO_MME             167
#define IDD_CONV_DATA_ASU               168
#define IDD_DIALOG1                     169
#define IDD_CHANGE_INFO_ASU             169
#define IDC_EDIT_TIME_BEGIN             1000
#define IDC_EDIT_TIME_END               1001
#define IDC_EDIT_TIME_ZOOM              1002
#define IDC_BUTTON_TIME_ZOOM_ALL        1003
#define IDC_BUTTON_TIME_ZOOM_IN         1004
#define IDC_BUTTON_TIME_ZOOM_OUT        1005
#define IDC_EDIT_LEVEL_BEGIN            1006
#define IDC_EDIT_LEVEL_BEGIN_X          1007
#define IDC_EDIT_LEVEL_MIN              1008
#define IDC_EDIT_TIME_CURSOR            1009
#define IDC_EDIT_LEVEL_END              1010
#define IDC_EDIT_LEVEL_END_X            1011
#define IDC_EDIT_LEVEL_MAX              1012
#define IDC_EDIT_LEVEL_CURSOR           1013
#define IDC_EDIT_SELECT_BEGIN           1014
#define IDC_EDIT_LEVEL_ZOOM             1015
#define IDC_EDIT_LEVEL_ZOOM_X           1016
#define IDC_BUTTON_LEVEL_ZOOM_OUT       1017
#define IDC_BUTTON_LEVEL_ZOOM_IN        1018
#define IDC_BUTTON_LEVEL_ZOOM_ALL       1019
#define IDC_EDIT_SELECT_END             1020
#define IDC_EDIT_LEVEL_BEGIN_Y          1021
#define IDC_EDIT_LEVEL_END_Y            1022
#define IDC_EDIT_RSU_X                  1023
#define IDC_EDIT_RSU_Y                  1024
#define IDC_EDIT_RSU_Z                  1025
#define IDC_EDIT_SCROLL_SPEED           1026
#define IDC_CHECK_SCROLL_START          1027
#define IDC_BUTTON_OCTAVE               1028
#define IDC_EDIT_ZERO_X                 1029
#define IDC_EDIT_DIR_X                  1030
#define IDC_BUTTON_FFT_OCTAVE           1031
#define IDC_BUTTON_SPECTRUM             1032
#define IDC_EDIT_RSU_D                  1033
#define IDC_EDIT_ZERO_Y                 1034
#define IDC_EDIT_DIR_Y                  1035
#define IDC_BUTTON_FFT_SPECTRUM         1036
#define IDC_BUTTON_CLOSE                1037
#define IDC_EDIT_RSU_Z2                 1038
#define IDC_EDIT_ZERO_Z                 1039
#define IDC_EDIT_DIR_Z                  1040
#define IDC_BUTTON_SPECTROGRAM          1041
#define IDC_EDIT_INFO_TAA_ID            1042
#define IDC_BUTTON_FFT_SPECTROGRAM      1043
#define IDC_COMBO_WINDOW_FUNCTION       1044
#define IDC_EDIT_INFO_ACQ_START_TIME    1045
#define IDC_STATIC_FFT_GRAPH            1046
#define IDC_EDIT_INFO_SAMPLING_RATE     1047
#define IDC_EDIT_INFO_CUT_OFF_FREQ      1048
#define IDC_EDIT_INFO_GAIN              1049
#define IDC_BUTTON_SELECT_ALL           1050
#define IDC_BUTTON_PRINT                1051
#define IDC_EDIT_INFO_POSITION          1052
#define IDC_BUTTON_TIME_CURSOR_TO_LEFT  1053
#define IDC_BUTTON_CSV                  1054
#define IDC_EDIT_DISP_BEGIN             1055
#define IDC_BUTTON_TIME_CURSOR_TO_RIGHT 1056
#define IDC_EDIT_DISP_BEGIN2            1057
#define IDC_EDIT_DISP_END               1058
#define IDC_EDIT_SPECTROGRAM_POINT_COUNT 1059
#define IDC_EDIT_DISP_END2              1060
#define IDC_EDIT_SPECTROGRAM_WIDTH      1061
#define IDC_EDIT_LEVEL_BEGIN_Z          1062
#define IDC_EDIT_LEVEL_END_Z            1063
#define IDC_LIST_DATA                   1064
#define IDC_EDIT_LEVEL_ZOOM_Y           1065
#define IDC_BUTTON_PREV_PAGE            1066
#define IDC_EDIT_LEVEL_ZOOM_Z           1067
#define IDC_BUTTON_NEXT_PAGE            1068
#define IDC_EDIT_PAGE_NO                1069
#define IDC_PROGRESS_BAR                1070
#define IDC_EDIT_DATA_BEGIN             1071
#define IDC_EDIT_DATA_END               1072
#define IDC_CHECK_DISP_X                1073
#define IDC_CHECK_DISP_Y                1074
#define IDC_CHECK_DISP_Z                1075
#define IDC_CHECK_DISP_S                1076
#define IDC_CHECK_DISP_X2               1077
#define IDC_CHECK_LIMIT_LINE_1          1078
#define IDC_CHECK_LIMIT_LINE_2          1079
#define IDC_CHECK_DISP_G                1080
#define IDC_STATIC_LINE_X               1081
#define IDC_STATIC_LINE_Y               1082
#define IDC_STATIC_LINE_Z               1083
#define IDC_STATIC_LINE_G               1084
#define IDC_COMBO_SAMPLE_RATE           1085
#define IDC_BUTTON_CONV                 1086
#define IDC_STATIC_SAMPLE_RATE          1087
#define IDC_COMBO_TARGET_DATA           1088
#define IDC_EDIT_MAI                    1089
#define IDC_STATIC_PAGE_CHANGE          1090
#define IDC_BUTTON_REF                  1091
#define IDC_BUTTON_ALL_SELECT           1092
#define IDC_EDIT_START                  1093
#define IDC_STATIC_PRINT                1094
#define IDC_EDIT_END                    1095
#define IDC_EDIT_UNITID                 1096
#define IDC_EDIT_SENSORID               1097
#define IDC_EDIT_SENSORID2              1098
#define IDC_EDIT_S_YY                   1099
#define IDC_EDIT_S_MM                   1100
#define IDC_EDIT_S_DD                   1101
#define IDC_EDIT_S_H                    1102
#define IDC_EDIT_S_M                    1103
#define IDC_EDIT_S_S                    1104
#define IDC_EDIT_E_YY                   1105
#define IDC_EDIT_E_MM                   1106
#define IDC_EDIT_E_DD                   1107
#define IDC_EDIT_E_H                    1108
#define IDC_EDIT_E_M                    1109
#define IDC_EDIT_E_S                    1110
#define IDC_COMBO_SENSOR                1111
#define IDC_COMBO_DATA                  1112
#define IDC_COMBO_CATEGORY              1113
#define IDC_MEAS_TIME                   1114
#define IDC_EDIT_TITLE                  1115
#define IDC_COMBO_MEASUREMENT_KIND      1116
#define IDC_EDIT_QUALITY                1117
#define IDC_EDIT_CURSOR_FREQ            1118
#define IDC_EDIT_ISS                    1119
#define IDC_EDIT_CURSOR_X               1120
#define IDC_EDIT_ISS2                   1121
#define IDC_EDIT_COMMENT                1122
#define IDC_EDIT_CURSOR_Y               1123
#define IDC_EDIT_DOWNLINK               1124
#define IDC_EDIT_CURSOR_Z               1125
#define IDC_CHECK_ZERO_HOSEI            1126
#define IDC_EDIT_FREQ_MIN               1127
#define IDC_EDIT_FREQ_MAX               1128
#define IDC_EDIT_CURSOR_Z2              1129
#define IDC_EDIT_CURSOR_G               1130
#define IDC_EDIT_FILTER_FREQ1           1131
#define IDC_EDIT_FILTER_FREQ2           1132
#define IDC_RADIO_FREQ_LINEAR           1133
#define IDC_RADIO_FREQ_LOG              1134
#define IDC_CHECK_ZOOM_X                1135
#define IDC_RADIO_LEVEL_LINEAR          1136
#define IDC_RADIO_LEVEL_LOG             1137
#define IDC_COMBO_FILTER_SHAPE          1138
#define IDC_BUTTON_FILTER_SET           1139
#define IDC_COMBO_FILTER_ORDER          1140
#define IDC_CHECK_ZOOM_Y                1141
#define IDC_BUTTON_FILTER_SET2          1142
#define IDC_BUTTON_TIME_SET             1143
#define IDC_COMBO_FILTER_BAND           1144
#define IDC_CHECK_ZOOM_Z                1145
#define IDC_EDIT_CURSOR_TIME            1146
#define IDC_DATA_LIST                   1147
#define IDC_DATA_LIST_COL               1148
#define IDC_DATA_LIST_ROW               1149
#define IDC_STATIC_ROW                  1150
#define IDC_STATIC_COL                  1151
#define IDC_BUTTON_INITIALIZE           1152
#define IDC_STATIC_LINE_D               1153
#define IDC_CHECK_DISP_D                1154
#define IDC_BUTTON_SELECT_MANUAL        1155
#define IDC_CHECK_ZERO_OFFSET_GRAPH     1156
#define IDC_EDIT_SCROLL_FREQ            1157
#define IDC_EDIT_DATA_FOLDER            1158
#define IDC_EDIT_MEAS_TIME              1159
#define IDC_EDIT_START_TIME             1160
#define IDC_EDIT_END_TIME               1161
#define IDC_STATIC_INFO_CUT_OFF_FREQ    1162
#define IDC_STATIC_INFO_GAIN            1163
#define IDC_STATIC_INFO_TAA_ID          1164
#define IDC_STATIC_DIR_X                1165
#define IDC_STATIC_DIR_Y                1166
#define IDC_STATIC_DIR_Z                1167
#define IDC_EDIT_DATA_FILE              1168
#define IDC_EDIT_SAMPLE_RATE            1169
#define IDC_STATIC_INFO_POSITION        1170
#define IDM_DELETE                      32771
#define IDM_RELOAD                      32777
#define IDM_CONVERT                     32778
#define IDM_OUTPUT_CSV                  32779
#define IDM_READ_FILE                   32782
#define IDM_PRINT                       32783
#define IDM_CLOSE                       32785
#define IDM_DISP_DIGITAL_DATA           32789
#define IDM_DISP_GRAPH                  32790
#define IDM_EXEC                        32801
#define IDM_DISP_TEMP_GRAPH             32807
#define IDM_UPDATE_INFO                 32810
#define IDM_CHANGE_INFO                 32811
#define IDM_REALTIME_START              32813
#define IDM_REALTIME_STOP               32815
#define IDM_EXPORT                      32821
#define IDM_CONVERT_MME                 32822
#define ID_32823                        32823
#define IDM_CONVERT_ASU                 32824

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        170
#define _APS_NEXT_COMMAND_VALUE         32825
#define _APS_NEXT_CONTROL_VALUE         1171
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
