//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MmeSend.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MMESEND_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_ANALOG_MONITOR              129
#define IDD_ACC_MONITOR                 130
#define IDD_HALT_ERROR                  131
#define IDC_BUTTON_MME_STATUS           1000
#define IDC_BUTTON_SEND_FILE            1001
#define IDC_EDIT_SEND_FILE              1002
#define IDC_BUTTON_REFERENCE            1003
#define IDC_EDIT_TIMER                  1004
#define IDC_BUTTON_SEND_STOP            1005
#define IDC_EDIT_COUNT                  1006
#define IDC_BUTTON_ERROR_STATUS         1007
#define IDC_BUTTON_MESSAGE              1008
#define IDC_BUTTON_TELEMETRY            1009
#define IDC_RADIO_PORT_NASA             1011
#define IDC_RADIO_PORT_HCOR             1012
#define IDC_EDIT1                       1014
#define IDC_EDIT_SESSION_NO             1014
#define IDC_EDIT_IP_ADDRESS             1015
#define IDC_EDIT_TELEMETRY_PAYLOAD_ID   1016
#define IDC_EDIT2                       1017
#define IDC_EDIT_TYPE                   1017
#define IDC_EDIT_TELEMETRY_DATA_ID      1018
#define IDC_EDIT3                       1019
#define IDC_EDIT_NATURE                 1019
#define IDC_EDIT_TELEMETRY_FRAME_ID     1020
#define IDC_EDIT4                       1021
#define IDC_EDIT_TASK_NAME              1021
#define IDC_EDIT_TELEMETRY_END_SEGMENT  1022
#define IDC_EDIT5                       1023
#define IDC_EDIT_ERROR_CODE             1023
#define IDC_EDIT_TELEMETRY_SEGMENT_COUNT 1024
#define IDC_EDIT6                       1025
#define IDC_EDIT_TIME                   1025
#define IDC_EDIT_TELEMETRY_TIMESTAMP    1026
#define IDC_EDIT7                       1027
#define IDC_EDIT_UNIT1_TEMP_SB          1027
#define IDC_EDIT_TELEMETRY_FINE_TIME    1028
#define IDC_EDIT8                       1029
#define IDC_EDIT_UNIT1_HEATER           1029
#define IDC_EDIT_TELEMETRY_MEASUREMENT_MODE 1030
#define IDC_EDIT9                       1031
#define IDC_EDIT_TELEMETRY_MEASUREMENT_RANGE 1032
#define IDC_EDIT10                      1033
#define IDC_EDIT_TELEMETRY_SAMPLING_RATE 1034
#define IDC_EDIT11                      1035
#define IDC_EDIT_TELEMETRY_STATUS_WORD  1036
#define IDC_EDIT12                      1037
#define IDC_EDIT_UNIT2_TEMP_X           1037
#define IDC_EDIT_TELEMETRY_DATA_NUM     1038
#define IDC_EDIT13                      1039
#define IDC_EDIT_UNIT2_TEMP_Y           1039
#define IDC_EDIT_STATUS_PAYLOAD_ID      1040
#define IDC_EDIT14                      1041
#define IDC_EDIT_UNIT2_TEMP_Z           1041
#define IDC_EDIT_STATUS_DATA_ID         1042
#define IDC_EDIT15                      1043
#define IDC_EDIT_UNIT2_TEMP_SB          1043
#define IDC_EDIT_STATUS_FRAME_ID        1044
#define IDC_EDIT16                      1045
#define IDC_EDIT_UNIT2_TEMP_HEATER      1045
#define IDC_EDIT_UNIT2_HEATER           1045
#define IDC_EDIT_STATUS_END_SEGMENT     1046
#define IDC_EDIT17                      1047
#define IDC_EDIT_STATUS_SEGMENT_COUNT   1048
#define IDC_EDIT18                      1049
#define IDC_EDIT_STATUS_TIMESTAMP       1050
#define IDC_EDIT19                      1051
#define IDC_EDIT_STATUS_FINE_TIME       1052
#define IDC_EDIT20                      1053
#define IDC_EDIT_UNIT3_TEMP_X           1053
#define IDC_BUTTON_TELEMETRY_ANALOG_MONITOR 1054
#define IDC_EDIT21                      1055
#define IDC_EDIT_UNIT3_TEMP_Y           1055
#define IDC_EDIT22                      1056
#define IDC_EDIT_UNIT1_ACC_X            1057
#define IDC_EDIT_UNIT1_TEMP_Z           1058
#define IDC_EDIT23                      1059
#define IDC_EDIT_UNIT3_TEMP_SB          1059
#define IDC_EDIT_UNIT1_ACC_Y            1060
#define IDC_EDIT_STATUS_DATA_NUM        1061
#define IDC_EDIT24                      1062
#define IDC_EDIT_UNIT3_HEATER           1062
#define IDC_EDIT_UNIT1_ACC_Z            1063
#define IDC_EDIT_STATUS_CONTROL_NAME    1064
#define IDC_EDIT_UNIT2_ACC_X            1065
#define IDC_EDIT_ERROR_PAYLOAD_ID       1066
#define IDC_EDIT_UNIT2_ACC_Y            1067
#define IDC_EDIT_ERROR_DATA_ID          1068
#define IDC_EDIT_UNIT2_ACC_Z            1069
#define IDC_EDIT_ERROR_FRAME_ID         1070
#define IDC_EDIT_UNIT3_ACC_X            1071
#define IDC_EDIT_ERROR_END_SEGMENT      1072
#define IDC_EDIT_UNIT3_ACC_Y            1073
#define IDC_EDIT_ERROR_SEGMENT_COUNT    1074
#define IDC_EDIT_UNIT3_ACC_Z            1075
#define IDC_EDIT_ERROR_TIMESTAMP        1076
#define IDC_EDIT_SEQ_COUNT              1077
#define IDC_EDIT_ERROR_FINE_TIME        1078
#define IDC_EDIT_UNIT1_                 1079
#define IDC_EDIT_ERROR_ERROR_CODE       1080
#define IDC_EDIT_ERROR_SUB_CODE         1081
#define IDC_EDIT_ERROR_DATA_NUM         1082
#define IDC_EDIT_ERROR_STATUS_WORD      1083
#define IDC_EDIT_MESSAGE_PAYLOAD_ID     1084
#define IDC_EDIT_MESSAGE_DATA_ID        1085
#define IDC_EDIT_MESSAGE_FRAME_ID       1086
#define IDC_EDIT_MESSAGE_END_SEGMENT    1087
#define IDC_EDIT_MESSAGE_SEGMENT_COUNT  1088
#define IDC_EDIT_MESSAGE_TIMESTAMP      1089
#define IDC_EDIT_MESSAGE_FINE_TIME      1090
#define IDC_EDIT_MESSAGE_DATA_NUM       1091
#define IDC_EDIT_MESSAGE_STATUS_WORD    1092
#define IDC_EDIT_MESSAGE_MESSAGE        1093
#define IDC_BUTTON_TELEMETRY_ACC_MONITOR 1094
#define IDC_EDIT_STATUS_CONTROL_DATA    1095
#define IDC_EDIT_STATUS_CURRENT_RANGE_ID 1096
#define IDC_EDIT_STATUS_DOWNLINK_NAME   1097
#define IDC_EDIT_STATUS_DOWNLINK_DATA   1098
#define IDC_EDIT_STATUS_TIMER_NAME      1099
#define IDC_EDIT_STATUS_TIMER_DATA      1100
#define IDC_EDIT_STATUS_START_NAME      1101
#define IDC_EDIT_STATUS_START_DATA      1102
#define IDC_EDIT_STATUS_END_NAME        1103
#define IDC_EDIT_STATUS_END_DATA        1104
#define IDC_BUTTON_STATUS_ANALOG_MONITOR 1105
#define IDC_EDIT_STATUS_STATUS_WORD     1106
#define IDC_EDIT_ERROR_TASK_NAME        1107
#define IDC_EDIT_ERROR_MESSAGE          1108
#define IDC_BUTTON_STATUS_HALT_ERROR    1109
#define IDC_BUTTON_MESSAGE_HALT_ERROR   1110
#define IDC_BUTTON_MESSAGE_MESSAGE      1111
#define IDC_BUTTON_TELEMETRY_SEND       1112
#define IDC_BUTTON_STATUS_SEND          1113
#define IDC_BUTTON9                     1114
#define IDC_BUTTON_ERROR_SEND           1115
#define IDC_BUTTON_MESSAGE_SEND         1116
#define IDC_BUTTON11                    1117
#define IDC_EDIT_STATUS_MEASURE_MODE_ID 1118
#define IDC_EDIT_STATUS_MEASURE_STATUS  1119
#define IDC_EDIT_UNIT1_TEMP_X           1120
#define IDC_EDIT_UNIT1_TEMP_Y           1121
#define IDC_EDIT_UNIT3_TEMP_Z           1122

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1123
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
