//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Nms.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_MEASURE_SET                 200
#define IDB_STATEICONS                  201
#define IDD_SPL                         202
#define IDD_INPUT_DEVICE                203
#define IDD_SAVE                        204
#define IDD_PEAK_LEVEL                  205
#define IDD_CHANGE_NOISE_SRC            206
#define IDD_NOISE_SOURCE                207
#define IDD_MANUAL_MODE                 208
#define IDD_GRAPH_FACTOR                209
#define IDD_NMS_FACTOR                  210
#define IDR_ZOOM_H                      211
#define IDR_ZOOM_V                      212
#define IDC_SAMPLING_LEVEL              1000
#define IDC_SAMPLING_TIME               1001
#define IDC_GRAPH                       1002
#define IDC_SAMPLING_TIME2              1003
#define IDC_SAMPLING_RATE               1004
#define IDC_SPL                         1005
#define IDC_TIMECONSTANT                1006
#define IDC_INPUT_DEVICE                1007
#define IDC_INPUT_SELECTOR              1008
#define IDC_INPUT_VOLUME                1009
#define IDC_FOLDER_LIST                 1010
#define IDC_WAVE_NOSAVE                 1011
#define IDC_PEAK_METER                  1012
#define IDC_NOISE_SRC_LIST              1013
#define IDC_TAUE_ORIGIN                 1014
#define IDC_IDENT_SPL                   1015
#define IDC_IDENT_TAUE                  1016
#define IDC_INTEGRATION_TIME            1017
#define IDC_RUNNING_STEP                1018
#define IDC_FREQ_WEIGHTING              1019
#define IDC_MAX_DELAY_TIME              1020
#define IDC_TAUE_INTERVAL               1021
#define IDC_TAUE_ENDLEVEL               1022
#define IDC_TAUE_ENDTIME                1023
#define IDC_IDENT_BEFORE_STEP           1024
#define IDC_IDENT_AFTER_STEP            1025
#define IDC_FACTOR_LIST                 1026
#define IDC_GRAPH_FACTOR                1027
#define IDC_ELAPSE_TIME                 1028
#define IDC_START_STOP                  1029
#define IDC_DB                          1030
#define IDC_ADD_NEW                     1031
#define IDC_START_DATE                  1032
#define IDC_START_TIME                  1033
#define IDC_START_DATE_TIME             1034
#define IDC_END_DATE                    1035
#define IDC_END_TIME                    1036
#define IDC_END_DATE_TIME               1037
#define IDC_START_CURRENT_TIME          1038
#define IDC_END_CURRENT_TIME            1039
#define IDC_PLAY_BACK                   1040
#define IDC_PRODUCT                     1041
#define IDC_COPYRIGHT                   1042
#define IDC_SCROLL_H                    1043
#define IDC_TIMING_PEAK                 1044
#define IDC_TIMING_LEVEL                1045
#define IDC_SAMPLING_TIME1              1046
#define IDC_RELATIVE_LEVEL              1047
#define IDC_NOISE_SOURCE_NAME           1048
#define IDC_xxxx_STORE                  1049
#define IDC_SCROLL_V                    1050
#define IDC_ZOOM_H                      1051
#define IDC_ZOOM_V                      1052
#define IDC_REGIST                      1053
#define IDC_CHANGE                      1054
#define IDC_NAME                        1055
#define IDC_PLACE                       1056
#define IDC_DATE                        1057
#define IDC_TITLE                       1058
#define IDC_COMMENT                     1059
#define IDC_FREQ                        1060
#define IDC_MICCAL_LIST                 1061
#define IDC_MICINFO                     1062
#define IDC_MICAMPINFO                  1063
#define IDC_FREQ_LIST                   1064
#define IDC_LEVEL                       1065
#define IDC_FREQ_RESPONSE               1066
#define IDC_READ                        1067
#define IDC_RESET                       1068
#define IDC_SIGNAL_OUT                  1069
#define IDC_INPUT_LEVEL                 1070
#define IDC_LEVEL_BAR                   1071
#define IDC_FILTER                      1072
#define IDC_SEPARATOR                   1073
#define IDC_PRODUCT_URL                 1074
#define IDC_COMPANY_URL                 1075
#define IDC_EMAIL_ADDR                  1076
#define IDC_DELETE                      1077
#define IDC_SETTING                     1078
#define IDC_FREQ_REGIST                 1079
#define IDC_FREQ_DELETE                 1080
#define IDC_CHECK1                      1081
#define IDS_STATUS                      3001
#define IDS_MAX_SPL                     3002
#define IDS_DATE                        3003
#define IDS_NAME                        3004
#define IDS_PLACE                       3005
#define IDS_TITLE                       3006
#define IDS_COMMENT                     3007
#define IDS_MICINFO                     3008
#define IDS_MICAMPINFO                  3009
#define IDS_AUTO_MEASURING              3010
#define IDS_STOPPED                     3011
#define IDS_NOT_CALC                    3012
#define IDS_IN_CALC                     3013
#define IDS_FINISHED                    3014
#define IDS_MANUAL_MEASURING            3015
#define IDS_START                       3016
#define IDS_STOP                        3017
#define IDS_ONLINE_MANUAL_CMD           3018
#define IDS_DOWNLOAD_MANUAL_CMD         3019
#define IDS_TECHNICAL_SUPPORT_CMD       3019
#define IDS_DOCUMENT_QA_CMD             3020
#define IDS_MSG_SOUNDINOUT              3021
#define IDS_ERR_TITLE                   3022
#define IDS_MSG_CHANGEDATA              3023
#define IDS_ERR_WRITEDATA               3024
#define IDS_MSG_DELTEMICCAL             3025
#define IDS_MSG_SAVEMICCAL              3026
#define IDS_MSG_SELECTMICCAL            3027
#define IDS_MSG_CHANGEMICCAL            3028
#define IDS_MSG_INPUTMICINFO            3029
#define IDS_MSG_UNDER0FREQ              3030
#define IDS_MSG_SAVEDATA                3031
#define IDS_MSG_INPUTNDATA              3032
#define IDS_MSG_MEAS_EXIT               3033
#define IDS_MSG_CALC_EXIT               3034
#define IDS_MSG_NOSAVE_EXIT             3035
#define IDS_MSG_CLEAR_DATA              3036
#define IDS_HELP_FILE                   9000
#define IDM_MEASURE_START               20000
#define IDM_MEASURE_STOP                20001
#define IDM_MEASURE_SET                 20002
#define IDM_INPUT_DEVICE                20003
#define IDM_INPUT_LEVEL                 20004
#define IDM_ONLINE_UPDATE               20005
#define IDM_ZOOM_FULL_H                 20006
#define IDM_ZOOM_IN_H                   20007
#define IDM_ZOOM_OUT_H                  20008
#define IDM_ZOOM_FULL_V                 20009
#define IDM_ZOOM_IN_V                   20010
#define IDM_ZOOM_OUT_V                  20011
#define IDM_ONLINE_MANUAL               20012
#define IDM_TECHNICAL_SUPPORT           20013
#define IDM_DOCUMENT_QA                 20014
#define IDM_VIEW_FACTOR                 20015
#define IDM_PEAK_LEVEL                  20016
#define IDM_CLEAR_DATA                  20017
#define IDM_TEMPLATE                    20018
#define IDM_RECALC                      20019
#define IDM_AUTO_LEARNING               20020
#define IDM_MANUAL_LEARNING             20021
#define IDM_CHANGE_NOISE_SRC            20022
#define IDM_MEASURE_MANUAL              20023
#define IDM_README                      20024
#define IDM_AUTO_CALC                   20025
#define IDM_READ_WAVE                   20026
#define IDM_xxxx_STORE                  20027
#define IDM_LICENSE_REGIST              20031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        213
#define _APS_NEXT_COMMAND_VALUE         20032
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           10000
#endif
#endif
