//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Common.rc
//
#define IDD_TEMP_ACF                    106
#define IDD_TEMP_IACF                   107
#define IDD_TEMPLATE                    108
#define IDD_TEMP_EXPORT                 109
#define IDD_TEMP_IMPORT                 110
#define IDC_HMOVE_CUR                   111
#define IDS_DEFAULTFONT                 4001
#define IDS_FREQUENCY                   4002
#define IDS_SPL                         4003
#define IDS_TIME                        4004
#define IDS_AMPLITUDE                   4005
#define IDS_FREQRESP                    4006
#define IDS_PHASE                       4007
#define IDS_DIRECTSOUND                 4008
#define IDS_FIRSTREFLECTION             4009
#define IDS_TAU                         4010
#define IDS_TAUE                        4011
#define IDS_NONE                        4013
#define IDS_AWEIGHTING                  4014
#define IDS_BWEIGHTING                  4015
#define IDS_CWEIGHTING                  4016
#define IDS_FLAT                        4017
#define IDS_REPLAY                      4018
#define IDS_INPUTWAVE                   4019
#define IDS_ONLINE_UPDATE               4020
#define IDS_MEASUREMENT_TIME            4021
#define IDS_DECISION                    4022
#define IDS_NOISE_VALUE                 4023
#define IDS_NUMBER                      4024
#define IDS_TAU1                        4025
#define IDS_PHI0                        4026
#define IDS_PHI1                        4027
#define IDS_TIACC                       4028
#define IDS_PHI_TAU                     4029
#define IDS_UNKNOWN                     4030
#define IDS_TAU2                        4031
#define IDS_TAU3                        4032
#define IDS_TAU4                        4033
#define IDS_TAU5                        4034
#define IDS_TAU6                        4035
#define IDS_TAU7                        4036
#define IDS_TAU8                        4037
#define IDS_TAU9                        4038
#define IDS_TAU10                       4039
#define IDS_PHI2                        4040
#define IDS_PHI3                        4041
#define IDS_PHI4                        4042
#define IDS_PHI5                        4043
#define IDS_PHI6                        4044
#define IDS_PHI7                        4045
#define IDS_PHI8                        4046
#define IDS_PHI9                        4047
#define IDS_PHI10                       4048
#define IDS_IMAGE_FILE                  4049
#define IDS_EXPORT_FILE                 4050
#define IDS_ONLINEUPDATE                4051
#define IDS_STOP2                       4052
#define IDS_LEVEL                       4053
#define IDS_SAVE_IMAGE_FILE             4054
#define IDS_MSG_CONVERTIRFILE           4100
#define IDS_MSG_CONVERTFOLDER           4101
#define IDS_MSG_CONVERTPRESET           4102
#define IDS_MSG_CONVERTMICCAL           4103
#define IDS_MSG_DELETECALCFILE          4104
#define IDS_MSG_CONVERTACFFILE          4105
#define IDS_MSG_CONVERTNMSFILE          4106
#define IDS_MSG_DELETEFOLDER            4107
#define IDS_MSG_CONVERTNSTMPFILE        4108
#define IDS_ERR_CREATEFOLDER            4200
#define IDS_ERR_OPENFOLDER              4201
#define IDS_ERR_CONVERFOLDER            4202
#define IDS_ERR_CREATEFOLDERINDEX       4203
#define IDS_ERR_READFOLDER              4204
#define IDS_ERR_WRITEFOLDER             4205
#define IDS_ERR_CREATEIRFILE            4207
#define IDS_ERR_OPENIRFILE              4208
#define IDS_ERR_CONVERTIRFILE           4209
#define IDS_ERR_READIRFILE              4210
#define IDS_ERR_WRITEIRFILE             4211
#define IDS_ERR_CREATECALCFILE          4212
#define IDS_ERR_OPENCALCFILE            4213
#define IDS_ERR_CREATECALCINDEX         4214
#define IDS_ERR_READCALCFILE            4215
#define IDS_ERR_FINDCALCFILE            4216
#define IDS_ERR_WRITECALCFILE           4217
#define IDS_ERR_CREATEIFFILE            4218
#define IDS_ERR_OPENIFFILE              4219
#define IDS_ERR_CREATEIFINDEX           4220
#define IDS_ERR_READIFFILE              4221
#define IDS_ERR_WRITEIFFILE             4222
#define IDS_STRING4223                  4223
#define IDS_ERR_DELETEIFFILE            4224
#define IDS_ERR_CREATEMICCAL            4225
#define IDS_ERR_OPENMICCAL              4226
#define IDS_ERR_CONVERTMICCAL           4227
#define IDS_ERR_CREATEMICCALINDEX       4228
#define IDS_ERR_READMICCAL              4229
#define IDS_ERR_WRITEMICCAL             4230
#define IDS_STRING4231                  4231
#define IDS_ERR_DELETEMICCAL            4232
#define IDS_ERR_CREATEPRESET            4233
#define IDS_ERR_OPENPRESET              4234
#define IDS_ERR_CONVERTPRESET           4235
#define IDS_ERR_CREATEPRESETINDEX       4236
#define IDS_ERR_READPRESET              4237
#define IDS_ERR_WRITEPRESET             4238
#define IDS_STRING4239                  4239
#define IDS_ERR_DELETEPRESET            4240
#define IDS_ERR_CREATEIRINDEX1          4241
#define IDS_ERR_CREATEIRINDEX2          4242
#define IDS_ERR_DELETEIRDATA            4243
#define IDS_ERR_FINDFOLDER              4244
#define IDS_ERR_DELETEFOLDER            4245
#define IDS_ERR_YMUPDATE                4246
#define IDS_ERR_ONLINEUPDATE            4247
#define IDS_ERR_CREATEACFFILE           4248
#define IDS_ERR_OPENACFFILE             4249
#define IDS_ERR_CONVERTACFFILE          4250
#define IDS_ERR_READACFFILE             4251
#define IDS_ERR_WRITEACFFILE            4252
#define IDS_ERR_CREATEACFINDEX1         4253
#define IDS_ERR_CREATEACFINDEX2         4254
#define IDS_ERR_CREATENMSFILE           4255
#define IDS_ERR_OPENNMSFILE             4256
#define IDS_ERR_CONVERTNMSFILE          4257
#define IDS_ERR_READNMSFILE             4258
#define IDS_ERR_WRITENMSFILE            4259
#define IDS_ERR_CREATENMSINDEX1         4260
#define IDS_ERR_CREATENMSINDEX2         4261
#define IDS_ERR_CREATENSTMPFILE         4262
#define IDS_ERR_OPENNSTMPFILE           4263
#define IDS_ERR_CONVERTNSTMPFILE        4264
#define IDS_ERR_READNSTMPFILE           4265
#define IDS_ERR_WRITENSTMPFILE          4266
#define IDS_ERR_CREATENSTMPINDEX        4267
#define IDS_ERR_NOISE_SOURCE            4268
#define IDS_ERR_EXPORT_FILE             4269
#define IDS_ERR_IMPORT_FILE             4270
#define IDS_ERR_DDE_INITIALIZE          4271
#define IDS_ERR_MMLIB                   4272
#define IDS_ERR_CREATECOLOR             4273
#define IDS_ERR_OPENCOLOR               4274
#define IDS_ERR_CREATECOLORINDEX        4275
#define IDS_ERR_READPCOLOR              4276
#define IDS_ERR_READCOLOR               4276
#define IDS_ERR_WRITECOLOR              4277
#define IDS_ERR_DELETECOLOR             4278
#define IDS_ERR_CREATEWAVEFORM          4279
#define IDS_ERR_OPENWAVEFORM            4280
#define IDS_ERR_CREATEWAVEFORMINDEX     4281
#define IDS_ERR_READWAVEFORM            4282
#define IDS_ERR_WRITEPRESET2            4283
#define IDS_ERR_WRITEWAVEFORM           4283
#define IDS_ASIO_DRIVER_BUSY            4284
#define IDS_ASIO_OPEN_ERROR             4285
#define IDS_ERR_NO_MMLIB_PATH           4286
#define IDS_ERR_EXEC_MMLIB              4287
#define IDS_ERR_CONVERTCALCFILE         4288
#define IDS_MSG_CONVERTCALCFILE         4289
#define IDC_UPDATE_TEMPLATE             4300
#define IDC_DELETE_TEMPLATE             4301
#define IDC_PHI0_UPPER_CHECK            4302
#define IDC_PHI0_LOWER_CHECK            4303
#define IDC_TAUE_UPPER_CHECK            4304
#define IDC_TAUE_LOWER_CHECK            4305
#define IDC_PHI1_UPPER_CHECK            4306
#define IDC_PHI1_LOWER_CHECK            4307
#define IDC_TAU1_UPPER_CHECK            4308
#define IDC_TAU1_LOWER_CHECK            4309
#define IDC_IMPORT                      4310
#define IDC_EXPORT                      4311
#define IDC_ALL_SELECT                  4312
#define IDC_ALL_REMOVE                  4313
#define IDB_LEFT_INDICATOR              4314
#define IDB_INDICATOR_LEFT              4315
#define IDC_MERGE                       4316
#define IDC_REPLACE                     4317
#define IDC_TEMPLATE_LIST               4318
#define IDC_PHI0_UPPER_LIMIT            4324
#define IDC_PHI0_LOWER_LIMIT            4325
#define IDC_PHI0_WEIGHTING              4326
#define IDC_TAUE_UPPER_LIMIT            4327
#define IDC_TAUE_LOWER_LIMIT            4328
#define IDC_TAUE_WEIGHTING              4329
#define IDC_PHI1_UPPER_LIMIT            4330
#define IDC_PHI1_LOWER_LIMIT            4331
#define IDC_PHI1_WEIGHTING              4332
#define IDC_TAU1_UPPER_LIMIT            4333
#define IDC_TAU1_LOWER_LIMIT            4334
#define IDC_TAU1_WEIGHTING              4335
#define IDC_NOISE_SOURCE                4337
#define IDC_PHI0_STANDARD               4338
#define IDC_TAUE_STANDARD               4339
#define IDC_PHI1_STANDARD               4341
#define IDC_TAU1_STANDARD               4342
#define IDC_SET_WEIGHTING               4347
#define IDB_RIGHT_INDICATOR             4348
#define IDB_INDICATOR_RIGHT             4349
#define IDC_FINGER                      4350
#define IDC_TAB                         4352
#define IDC_IACC_STANDARD               4353
#define IDC_IACC_UPPER_CHECK            4354
#define IDC_IACC_UPPER_LIMIT            4355
#define IDC_IACC_LOWER_CHECK            4356
#define IDC_IACC_LOWER_LIMIT            4357
#define IDC_WIACC_STANDARD              4358
#define IDC_WIACC_UPPER_CHECK           4359
#define IDC_WIACC_UPPER_LIMIT           4360
#define IDC_WIACC_LOWER_CHECK           4361
#define IDC_WIACC_LOWER_LIMIT           4362
#define IDC_TIACC_STANDARD              4363
#define IDC_TIACC_UPPER_CHECK           4364
#define IDC_TIACC_UPPER_LIMIT           4365
#define IDC_TIACC_LOWER_CHECK           4366
#define IDC_TIACC_LOWER_LIMIT           4367
#define IDC_IACC_WEIGHTING              4368
#define IDC_WIACC_WEIGHTING             4369
#define IDC_TIACC_WEIGHTING             4370
#define IDS_PAYPAL_EA                   4390
#define IDS_PAYPAL_SA                   4391
#define IDS_PAYPAL_RA                   4392
#define IDS_PAYPAL_RAL                  4393
#define IDS_xxxx_STORE                  4394

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        112
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         4371
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
