<html>

<head>
<title>ありがとうございました！</title>
<meta HTTP-EQUIV="Content-Type" Content="text/html; charset=x-sjis">
<meta HTTP-EQUIV="Pragma" Content="no-cache">
<STYLE TYPE="text/css">
<!--
A:link		{color: #0000FF;text-decoration: none;}
A:visited	{color: #0000FF;text-decoration: none;}
A:hover		{color: #ff0000;text-decoration: underline;}
-->
</STYLE>
</head>

<body bgcolor="#FFFFFF" topmargin="0">
<div align="center">
  <center>
  <table border="0" cellpadding="0" cellspacing="0" width="100" height="20">
    <tr>
      <td></td>
    </tr>
  </table>
  </center>
</div>
<div align="center"><center>

<table border="1" width="400" height="169" cellspacing="0" bordercolor="#BEBEFF" bordercolorlight="#BEBEFF" bordercolordark="#BEBEFF">
  <tr>
    <td width="400" height="169" valign="middle" align="center"><font size="+1"><p align="center"><strong><br>
      </strong>
    </font><strong><font size="+2" color="#FF8080">めるめる・net
      への仮登録を<br>
      受け付けました。<br>
    誠にありがとうございます。</font></strong></p>
</center><p align="left">　これより貴誌を複数号にわたって熟読させていただきます。その後、審査結果をお知らせいたします。本登録のご案内により再度システムや詳細な契約内容をご確認いただき、その時点でご承諾をいただけば本登録となって、広告の配信が開始されます。</p>
    <p align="left">　また、仮登録いただきましても、広告主との関係で広告を依頼することが保証できないメルマガさんには、本登録をお断りするケースもありますことを、あらかじめご承知置きください。</p>
    <center>

<p align="center"><font size="3" color="#000080">今後ともよろしくお願いいたします。</font></p>
      <div align="center">
        <table border="0" cellpadding="0" cellspacing="0" width="350">
          <tr>
            <td>
              <hr color="#BEBEFF" width="300" size="1">
            </td>
          </tr>
          <tr>
            <td>
    <p align="center"><font size="1" color="#000000">めるめる・net事務局</font>
            </td>
          </tr>
          <tr>
            <td height="40">
              <p align="center"><font size="1" color="#000000"><a href="mailto:office@melmel.net?subject=めるめる・net問合せ">ご不明な点などございましたらこちらまで</a></font></td>
          </tr>
        </table>
      </div>
    </td>
  </tr>
</table>
  </div>

<br>
<center><input type="button" value="トップへ戻る" onClick="location.href='../index.html'"></center>

</body>
</html>
