<%@ LANGUAGE="VBScript" %>
<html>

<head>
<meta HTTP-EQUIV="Content-Type" Content="text/html; charset=x-sjis">
<meta HTTP-EQUIV="Pragma" Content="no-cache">
<title>既にご応募頂いております。</title>
<STYLE TYPE="text/css">
<!--
A:link		{color: #0000FF;text-decoration: none;}
A:visited	{color: #0000FF;text-decoration: none;}
A:hover		{color: #ff0000;text-decoration: underline;}
-->
</STYLE>
</head>

<body bgcolor="#FFFFFF" topmargin="0">

<div align="center">
  <center>
  <table border="0" cellpadding="0" cellspacing="0" width="100" height="20">
    <tr>
      <td></td>
    </tr>
  </table>
  </center>
</div>
<div align="center"><center>

<table border="1" width="377" height="169" cellspacing="0" bordercolor="#BEBEFF" bordercolorlight="#BEBEFF" bordercolordark="#BEBEFF">
  <tr>
    <td width="377" height="169" valign="middle" align="center"><font size="+1"><p align="center"><strong><br>
      </strong>
    </font><strong><font size="+2" color="#800000">あなた様のご登録は既に<br>
    受付させて頂いております。</font></strong></p>
    <p align="center">この度は誠にありがとうございました。</p>
      <div align="center">
        <table border="0" cellpadding="0" cellspacing="0" width="350">
          <tr>
            <td>
              <hr color="#BEBEFF" width="300" size="1">
            </td>
          </tr>
          <tr>
            <td>
    <p align="center"><font size="1" color="#000000">めるめる・net事務局</font>
            </td>
          </tr>
          <tr>
            <td height="40">
              <p align="center"><font size="1" color="#000000"><a href="mailto:taguchi@dhmail2.xxxxxxx.co.jp?subject=めるめる・net問合せ">ご不明な点などございましたらこちらまで</a></font></td>
          </tr>
        </table>
      </div>
    </td>
  </tr>
</table>
</center></div>

<br>
<center><input type="button" value="トップへ戻る" onClick="location.href='../index.html'"></center>

</body>
</html>
