//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Sas.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_FOLDER                      200
#define IDD_IMP_FACTOR                  201
#define IDD_GRAPH_FREQ                  202
#define IDD_GRAPH_ECHO                  203
#define IDD_GRAPH_IACC                  204
#define IDD_CALC_IMP                    205
#define IDB_IMAGE_LIST                  206
#define IDD_CHANGE_TSUB                 207
#define IDD_CHANGE_WIACC                208
#define IDD_CALC_ACF                    209
#define IDD_PROGRESS                    210
#define IDD_GRAPH_IR                    211
#define IDD_GRAPH_PREF                  212
#define IDD_GRAPH_PARAM                 213
#define IDD_ACF_FACTOR                  214
#define IDD_GRAPH_FACTOR                215
#define IDD_NMS_FACTOR                  216
#define IDD_CALC_NMS                    217
#define IDD_GRAPH_ACF                   218
#define IDD_GRAPH_IACF                  219
#define IDD_NMS_SCREEN_COPY             220
#define IDD_ACF_SCREEN_COPY             221
#define IDD_GRAPH_MTF                   222
#define IDD_GRAPH_WAVE                  223
#define IDD_GRAPH_SPEC                  224
#define IDR_ZOOM_H                      225
#define IDR_ZOOM_V                      226
#define IDD_PARAM1                      227
#define IDD_PARAM2                      228
#define IDD_IMP_SCREEN_COPY             229
#define IDR_LISTVIEW                    230
#define IDR_LEFTVIEW                    232
#define IDD_ACF_MARKER                  234
#define IDR_ADD_MARKER                  235
#define IDR_EDIT_MARKER                 236
#define IDC_MMLIB                       1000
#define IDC_PREV_DATA                   1001
#define IDC_NEXT_DATA                   1002
#define IDC_SELECT_DATA                 1003
#define IDC_SCREEN_COPY                 1004
#define IDC_FOLDER_LIST                 1005
#define IDC_GRAPH                       1006
#define IDC_PROGRESS1                   1007
#define IDC_GRAPH_IACC                  1008
#define IDC_CALC_NO                     1009
#define IDC_CALC_SELECT                 1010
#define IDC_CALC_ALL                    1011
#define IDC_DT1_MINTIME                 1012
#define IDC_TSUB_END                    1013
#define IDC_ABORT                       1014
#define IDC_TSUB_NOISE                  1015
#define IDC_IACC_WLEVEL                 1016
#define IDC_PARAM_LIST                  1017
#define IDC_1OCT                        1018
#define IDC_3OCT                        1019
#define IDC_CHANGE                      1020
#define IDC_LEFT_T0                     1021
#define IDC_LEFT_T1                     1022
#define IDC_RIGHT_T0                    1023
#define IDC_RIGHT_T1                    1024
#define IDC_START_FREQ                  1025
#define IDC_END_FREQ                    1026
#define IDC_MESSAGE                     1027
#define IDC_RIGHT                       1028
#define IDC_LEFT_RIGHT                  1029
#define IDC_LEFT                        1030
#define IDC_REGRESS                     1031
#define IDC_TSUB_AUTO                   1032
#define IDC_IR_LEFT                     1033
#define IDC_IR_RIGHT                    1034
#define IDC_GRAPH_IR                    1035
#define IDC_GRAPH_EE                    1036
#define IDC_SCALE                       1037
#define IDC_GRAPH_PREF                  1038
#define IDC_BESTSPL                     1039
#define IDC_TAUE                        1040
#define IDC_S1                          1041
#define IDC_S2                          1042
#define IDC_S3                          1043
#define IDC_S4                          1044
#define IDC_S                           1045
#define IDC_CALC                        1046
#define IDC_BEST_TAUE                   1047
#define IDC_GRAPH_PARAM                 1048
#define IDC_PARAM_SPL                   1049
#define IDC_PREF_SPL                    1050
#define IDC_PREF_TAUE                   1051
#define IDC_SPL_REFDATA                 1052
#define IDC_PARAM_A                     1053
#define IDC_SPL_REFLEVEL                1054
#define IDC_PARAM_TSUB                  1055
#define IDC_PARAM_IACC                  1056
#define IDC_MEAN                        1057
#define IDC_IDENT_SPL                   1058
#define IDC_PARAM_WIACC                 1059
#define IDC_AFILTER                     1060
#define IDC_IDENT_TAUE                  1061
#define IDC_PARAM_TIACC                 1062
#define IDC_CHANGE_WIACC                1063
#define IDC_INTEGRATION_TIME            1064
#define IDC_CALC_CYCLE                  1065
#define IDC_FREQ_FILTER                 1066
#define IDC_MAX_DELAY_TIME              1067
#define IDC_TAUE_INTERVAL               1068
#define IDC_TAUE_ENDLEVEL               1069
#define IDC_TAUE_ENDTIME                1070
#define IDC_PHI0_REFDATA                1071
#define IDC_IDENT_BEFORE_STEP           1072
#define IDC_PHI0_REFLEVEL               1073
#define IDC_IDENT_AFTER_STEP            1074
#define IDC_FACTOR_LIST                 1075
#define IDC_GRAPH_FACTOR                1076
#define IDC_RUNNING_STEP                1077
#define IDC_DELETE                      1078
#define IDC_FREQ_LEFT                   1079
#define IDC_FREQ_RIGHT                  1080
#define IDC_KIND_ALL                    1081
#define IDC_KIND_IR                     1082
#define IDC_KIND_ACF                    1083
#define IDC_GRAPH_ECHO                  1084
#define IDC_KIND_NMS                    1085
#define IDC_GRAPH_ACF                   1086
#define IDC_LOG                         1087
#define IDC_TAUE_ORIGIN                 1088
#define IDC_TAU1_A                      1089
#define IDC_TAU1_B                      1090
#define IDC_TAU1_A2                     1091
#define IDC_PLAYBACK                    1092
#define IDC_SC_WINDOW                   1093
#define IDC_SC_GRAPH                    1094
#define IDC_SC_FRAME                    1095
#define IDC_SC_PHI0                     1096
#define IDC_SC_TAUE                     1097
#define IDC_SC_TAU1                     1098
#define IDC_SC_PHI1                     1099
#define IDC_SC_SPL                      1100
#define IDC_SC_IACC                     1101
#define IDC_SC_TAUIACC                  1102
#define IDC_SC_WIACC                    1103
#define IDC_SC_ACF                      1104
#define IDC_SC_IACF                     1105
#define IDC_SC_MULTI                    1106
#define IDC_SC_COLUMNS                  1107
#define IDC_SC_COLSPACE                 1108
#define IDC_SC_ROWSPACE                 1109
#define IDC_COPYRIGHT                   1110
#define IDC_PRODUCT                     1111
#define IDC_SC_COLUMNS2                 1111
#define IDC_SCROLL_V                    1112
#define IDC_SC_COLSPACE2                1112
#define IDC_SCROLL_H                    1113
#define IDC_SC_ROWSPACE2                1113
#define IDC_ZOOM_H                      1114
#define IDC_ZOOM_V                      1115
#define IDC_xxxx_STORE                  1116
#define IDC_SN_RATIO                    1117
#define IDC_SN_RATIO_VAL                1118
#define IDC_STI_L                       1119
#define IDC_MTF_LEFT                    1120
#define IDC_MTF_RIGHT                   1121
#define IDC_STI_R                       1122
#define IDC_GRAPH_LEFT                  1123
#define IDC_GRAPH_RIGHT                 1124
#define IDC_SAMPLING                    1125
#define IDC_MEASURE_TIME                1126
#define IDC_MEASURE_NUM                 1127
#define IDC_CHANNEL                     1128
#define IDC_BIT                         1129
#define IDC_NAME                        1130
#define IDC_PLACE                       1131
#define IDC_DATE                        1132
#define IDC_FOLDER_TITLE                1133
#define IDC_FOLDER_COMMENT              1134
#define IDC_TITLE                       1135
#define IDC_COMMENT                     1136
#define IDC_TIME                        1137
#define IDC_PRODUCT_URL                 1138
#define IDC_COMPANY_URL                 1139
#define IDC_EMAIL_ADDR                  1140
#define IDC_G_REFLEVEL                  1141
#define IDC_T_CUSTOM1                   1142
#define IDC_T_CUSTOM2                   1143
#define IDC_C_CUSTOM                    1144
#define IDC_CALC_CONDITION              1145
#define IDC_CSV_OUTPUT                  1146
#define IDC_PARAM_G                     1147
#define IDC_PARAM_T20                   1148
#define IDC_PARAM_T30                   1149
#define IDC_PARAM_T_CUSTOM              1150
#define IDC_PARAM_EDT                   1151
#define IDC_PARAM_C50                   1152
#define IDC_PARAM_C80                   1153
#define IDC_PARAM_C_CUSTOM              1154
#define IDC_PARAM_D50                   1155
#define IDC_PARAM_TS                    1156
#define IDC_PARAM_IACCE                 1157
#define IDC_PARAM_IACCL                 1158
#define IDC_STI_M_L                     1159
#define IDC_STI_M_R                     1160
#define IDC_STI_F_L                     1161
#define IDC_STI_F_R                     1162
#define IDC_RASTI_L                     1163
#define IDC_RASTI_R                     1164
#define IDC_SC_IMP                      1165
#define IDC_SC_ECHO                     1166
#define IDC_SC_FREQ                     1167
#define IDC_SC_PREF                     1168
#define IDC_SC_MTF                      1169
#define IDC_SC_PARAM                    1170
#define IDC_CALC_MEASUREMENT            1171
#define IDC_EDIT_TITLE                  1172
#define IDC_EDIT_COMMENT                1173
#define IDS_ABOUTBOX                    3001
#define IDS_ABSVALUE                    3002
#define IDS_MAXVALUE                    3003
#define IDS_EXPIRE                      3004
#define IDS_CALCULATING                 3005
#define IDS_TXTCSV                      3006
#define IDS_DATE                        3007
#define IDS_CALC                        3008
#define IDS_REVLEVEL                    3009
#define IDS_IDS_REVLEVEL                3010
#define IDS_WITHOUTNOISE                3011
#define IDS_WITHNOISE                   3012
#define IDS_REGRESSIONLINE              3013
#define IDS_NAME                        3014
#define IDS_PLACE                       3015
#define IDS_SCALE                       3016
#define IDS_ECHOTIMEPATTERN             3017
#define IDS_DECAYCURVE                  3018
#define IDS_SCHROEDER                   3019
#define IDS_SPECTRUM                    3020
#define IDS_LEFTCHANNEL                 3021
#define IDS_RIGHTCHANNEL                3022
#define IDS_CCF                         3023
#define IDS_IR                          3024
#define IDS_LEFTIR                      3025
#define IDS_TITLE                       3026
#define IDS_COMMENT                     3027
#define IDS_SAMPLING                    3028
#define IDS_RIGHTIR                     3029
#define IDS_CCF2                        3030
#define IDS_TAB_IR                      3031
#define IDS_TAB_REVERBERATION           3032
#define IDS_TAB_CCF                     3033
#define IDS_TAB_SPECTRUM                3034
#define IDS_TAB_PREFERENCE              3035
#define IDS_TAB_PARAMETERS              3036
#define IDS_LRAVERAGE                   3037
#define IDS_TAUEPREF                    3038
#define IDS_OPTIMUMTAUE                 3039
#define IDS_MAXPREF                     3040
#define IDS_PREFVALUE                   3041
#define IDS_DT1LR                       3042
#define IDS_DT1L                        3043
#define IDS_DT1R                        3044
#define IDS_DT1                         3045
#define IDS_TYPE                        3046
#define IDS_TYPE_IR                     3047
#define IDS_TYPE_ACF                    3048
#define IDS_TYPE_NMS                    3049
#define IDS_TYPE_DB                     3050
#define IDS_MOD_FREQUENCY               3051
#define IDS_WAVE                        3052
#define IDS_ONLINE_MANUAL_CMD           3053
#define IDS_DOWNLOAD_MANUAL_CMD         3054
#define IDS_TECHNICAL_SUPPORT_CMD       3054
#define IDS_DOCUMENT_QA_CMD             3055
#define IDS_MSG_TAUE                    3056
#define IDS_MSG_SELECTDATA              3057
#define IDS_MSG_SELECTFOLDER            3058
#define IDS_MSG_SAVECALC                3059
#define IDS_MSG_CANCELACTION            3060
#define IDS_ERR_READDATA                3061
#define IDS_PARAM1                      3062
#define IDS_PARAM2                      3063
#define IDS_MSG_DELETESELECTDATA        3064
#define IDS_ERR_TITLE                   3065
#define IDS_DELETE_MARKER               3066
#define IDS_HELP_FILE                   9000
#define IDM_CALC                        20000
#define IDM_OUTPUT                      20001
#define IDM_VIEW_UPDATE                 20002
#define IDM_PARAM_DISP                  20003
#define IDM_PARAM_CALC                  20004
#define IDM_PARAM_OUTPUT                20005
#define IDM_ONLINE_UPDATE               20006
#define IDM_ZOOM_FULL_H                 20007
#define IDM_ZOOM_IN_H                   20008
#define IDM_ZOOM_OUT_H                  20009
#define IDM_ZOOM_FULL_V                 20010
#define IDM_ZOOM_IN_V                   20011
#define IDM_ZOOM_OUT_V                  20012
#define IDM_ONLINE_MANUAL               20013
#define IDM_TECHNICAL_SUPPORT           20014
#define IDM_DOCUMENT_QA                 20015
#define IDM_TEMPLATE                    20016
#define IDM_README                      20017
#define IDM_xxxx_STORE                  20018
#define IDM_LICENSE_REGIST              20019
#define IDM_FILE_DELETE                 20020
#define IDM_PARAM_CALC2                 20021
#define IDM_FILE_TITLE_CHANGE           20022
#define IDM_FILE_CHANGE_TITLE           20023
#define IDM_PLAY                        20024
#define IDM_ADD_ACF_MARKER              20025
#define IDM_EDIT_ACF_MARKER             20026
#define IDM_DELETE_ACF_MARKER           20027
#define ID_MENU_20028                   20028
#define IDM_REPLAY                      20029
#define IDM_PLAYBACK                    20030
#define IDM_PLAYBACK_ACF_MARKER         20031
#define AFX_IDS_UNTITLED2               61444

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        238
#define _APS_NEXT_COMMAND_VALUE         20032
#define _APS_NEXT_CONTROL_VALUE         1175
#define _APS_NEXT_SYMED_VALUE           10000
#endif
#endif
