<?php

//ログイン login.php
$em_login_1 = "すべての項目を入力してください。";
$em_login_2 = "入力した基本メールアドレスは登録されていないようです。";
$em_login_3 = "パスワードが正しくないようです。";

//発行者情報変更 hakkousya_henkou1.php hakkousya-kaijyo.php
$em_henkou_1 =  "指定された発行者ＩＤはありません。";

//発行者解除確認 kaijyo-kakunin.php
$em_kaijyo_1 =  "指定された発行者ＩＤはありません。";
$em_kaijyo_2 =  "指定されたデータには、メールマガジンが登録されております。";

//解除理由 kaijyo-kanryou.php
$em_kaijyo_3 =  "解除理由を選択、もしくは入力してください。";
$em_kaijyo_4 =  "指定されたパスワードが違います。";
$em_kaijyo_5 =  "すでに削除済みです。";
$em_kaijyo_6 =  "指定されたデータには、メールマガジンが登録されております。";

//マガジン修正 magazine4.php
$em_magazine_1 =  "ご指定のメールアドレスで登録された購読メルマガは無いようです。";

//マガジンメンテナンス mag-status.php mag-sakujyo.php mag-sakujyo-ok.php
$em_mag_1 = "指定されたメールアドレスは登録されておりません。";
$em_mag_2 = "指定されたメルマガＩＤはありません。";
$em_mag_3 = "指定された発行者ＩＤはありません。";
$em_mag_4 = "「廃刊理由」は全角２０文字以内で入力してください。";
$em_mag_5 = "データの削除ができませんでした。";
$em_mag_6 = "すでに削除済みです。";
$em_mag_7 = "廃刊理由を選択、もしくは入力してください。";
$em_mag_8 = "指定したパスワードが違います。";

//マガジン配信 mag-haishin.php
$em_haishin_1 =	"は過ぎているようです。";
$em_haishin_2 =	"は存在しないようです。";
$em_haishin_3 = "テスト配信を行ってください。";
$em_haishin_4 = "は取り消されているか、配信済みです。";

//マガジン廃刊休刊　mag-yasumi.php mag-yasumi-ok.php
$em_yasumi_1 = "指定されたメルマガＩＤはありません。";
$em_yasumi_2 = "指定された発行者ＩＤはありません。";
$em_yasumi_3 = "「休刊理由」は全角２０文字以内で入力してください。";
$em_yasumi_4 = "「休刊理由」を選択、もしくは記入してください。";
$em_yasumi_5 = "休刊処理ができませんでした。";
$em_yasumi_6 = "すでに削除済みです。";
$em_yasumi_7 = "指定したパスワードが違います。";
$em_yasumi_8 = "指定された発行者ＩＤはありません。";

?>
