//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Rta.rc
//
#define IDC_OUTPUT_FILE                 3
#define IDM_ABOUTBOX                    0x0010
#define IDM_ONLINE_UPDATE               0x0020
#define IDM_FONT_ENLARGE                0x0030
#define IDM_FONT_REDUCE                 0x0040
#define IDD_ABOUTBOX                    100
#define IDD_RTA_DIALOG                  102
#define IDR_MAINFRAME                   128
#define IDD_SG_TONE                     200
#define IDD_SG_NOISE                    201
#define IDD_SG_SWEEP                    202
#define IDD_SG                          203
#define IDD_FFT                         204
#define IDB_RTA_OCT_HOLD_LEFT           205
#define IDB_RTA_OCT_HOLD_RIGHT          206
#define IDD_IMPULSE                     207
#define IDD_SG_PULSE                    208
#define IDD_OS                          209
#define IDD_SAVE_IR                     210
#define IDD_FOLDER                      211
#define IDD_IFA_SAVE                    212
#define IDD_IFA_SET                     213
#define IDD_MICCAL                      214
#define IDD_PRESET                      215
#define IDR_ZOOM_H                      216
#define IDD_PRESET_SAVE                 217
#define IDD_ACF                         218
#define IDR_TIME_MENU                   219
#define IDD_IR_ASSIST                   220
#define IDD_SAVE_ACF                    221
#define IDD_LOAD_DATA                   222
#define IDR_MAIN_MENU                   223
#define IDB_RTA_OCT_LEFT                224
#define IDB_RTA_OCT_RIGHT               225
#define IDB_RTA_OCT_PEAK_LEFT           226
#define IDB_RTA_OCT_PEAK_RIGHT          227
#define IDD_DST                         228
#define IDD_DST_MANUAL                  229
#define IDD_DST_FREQ                    230
#define IDD_DST_LEVEL                   231
#define IDD_REC                         232
#define IDD_DATA_RECORD                 233
#define IDI_SCREEN_SHOT                 234
#define IDB_SCREEN_SHOT                 235
#define IDD_SG_SCALE                    236
#define IDD_SG_SYNTH                    237
#define IDD_SETTING_FONT                238
#define IDD_SG_WAVE                     239
#define IDD_WAVE_EDIT                   240
#define IDR_ZOOM_V                      241
#define IDD_MICCAL2                     242
#define IDI_FFT_WINDOW                  243
#define IDD_FRE                         244
#define IDD_FRE_SWEEP                   245
#define IDD_FRE_NOISE                   246
#define IDD_FRE_SPOT                    247
#define IDD_FILTER                      248
#define IDD_OS_CAL                      249
#define IDR_SCREEN_SHOT_MENU            250
#define IDD_WAVE_EDIT_MANUAL            251
#define IDD_WAVE_EDIT_FM                252
#define IDD_SETTING_DEVICE              253
#define IDR_WAVE_EDIT_MENU              254
#define IDD_DATA_BACKUP                 255
#define IDD_DATA_RESTORE                256
#define IDD_INIT_SETTINGS               257
#define IDD_ACF_REALTIME                258
#define IDD_ACF_REALTIME_CALC           259
#define IDR_ACF_REALTIME_MENU           260
#define IDD_FFT_LEVEL                   261
#define IDD_FFT_FREQ                    262
#define IDR_ACCELERATOR1                263
#define IDR_ACCELERATOR2                264
#define IDR_TOOLBAR_MAIN                265
#define IDD_AUTO_REC                    267
#define IDC_DELETE                      1000
#define IDC_FOLDER                      1001
#define IDC_SETTING                     1002
#define IDC_OVERWRITE                   1003
#define IDC_FREQ_REGIST                 1004
#define IDC_FREQ_DELETE                 1005
#define IDC_SQUARE                      1006
#define IDC_SINWAVE                     1007
#define IDC_TRIANGLE                    1008
#define IDC_WHITE_NOISE                 1009
#define IDC_PINK_NOISE                  1010
#define IDC_STREO                       1011
#define IDC_MONO                        1012
#define IDC_INVERSE                     1013
#define IDC_START_FREQ                  1014
#define IDC_END_FREQ                    1015
#define IDC_LOOP                        1016
#define IDC_SAW                         1017
#define IDC_SWEEP_SPEED                 1018
#define IDC_SG_LSLIDER                  1019
#define IDC_SG_RSLIDER                  1020
#define IDC_SG_LLEVEL                   1021
#define IDC_SG_RLEVEL                   1022
#define IDC_RA_ACF                      1023
#define IDC_RA_PRESET                   1024
#define IDC_SFREQ_R                     1025
#define IDC_RENDOU                      1026
#define IDC_EFREQ_R                     1027
#define IDC_FFT_TAB                     1028
#define IDC_RENDOU_F                    1029
#define IDC_SG_TAB                      1030
#define IDC_BTN_START                   1031
#define IDC_BTN_STOP                    1032
#define IDC_FFT_MAX_FREQ                1033
#define IDC_FFT_MIN_FREQ                1034
#define IDC_FFT_MAX_LEVEL               1035
#define IDC_FFT_MIN_LEVEL               1036
#define IDC_FFT_MAX_LEVEL2              1036
#define IDC_FFT_LOG_SCALE               1037
#define IDC_FFT_LINEAR_SCALE            1038
#define IDC_FFT_AUTO_FREQ               1039
#define IDC_FFT_AUTO_LEVEL              1040
#define IDC_FFT_WINFUNC                 1041
#define IDC_FFT_FFT_SIZE                1042
#define IDC_FFT_FILTER                  1043
#define IDC_FFT_PEAK_FREQ_LEFT          1044
#define IDC_FFT_PEAK_LEVEL_LEFT         1045
#define IDC_FFT_PEAK_DISP               1046
#define IDC_FFT_PEAK_LEVEL_RIGHT        1047
#define IDC_FFT_PEAK_FREQ_RIGHT         1048
#define IDC_FFT_MESSAGE                 1049
#define IDC_FFT_PEAK_HOLD               1050
#define IDC_FFT_RES_FREQ                1051
#define IDC_FFT_RES_TIME                1052
#define IDC_FFT_TIME_FWD                1053
#define IDC_FFT_TIME_BWD                1054
#define IDC_FFT_TIME_DATA_NUM           1055
#define IDC_IMP_SCROLL                  1056
#define IDC_IMPALSE_L                   1057
#define IDC_IMP_ZOOM_IN                 1058
#define IDC_IMPALSE_R                   1059
#define IDC_IMP_ZOOM_OUT                1060
#define IDC_IMP_FULL                    1061
#define IDC_MESSAGE                     1062
#define IDC_PULSE_POSITIVE              1063
#define IDC_PULSE_NEGATIVE              1064
#define IDC_PULSE_CONTINUE              1065
#define IDC_PULSE_CYCLE                 1066
#define IDC_PULSE_WIDTH                 1067
#define IDC_MAX_DELAY_TIME              1068
#define IDC_PULSE_NUM                   1069
#define IDC_TAUE_INTERVAL               1070
#define IDC_PULSE_BOTH                  1071
#define IDC_TAUE_ENDLEVEL               1072
#define IDC_OS_SCREEN                   1073
#define IDC_TAUE_ENDTIME                1074
#define IDC_OS_SWEEP                    1075
#define IDC_OS_SWEEP2                   1076
#define IDC_OS_DELAY                    1077
#define IDC_OS_DELAY2                   1078
#define IDC_OS_TRIG_CH1                 1079
#define IDC_FACTOR_LIST                 1080
#define IDC_OS_TRIG_CH2                 1081
#define IDC_GRAPH_PHI1                  1082
#define IDC_ZOOM_H                      1083
#define IDC_GRAPH_PHI0                  1084
#define IDC_RUNNING_STEP                1085
#define IDC_OS_TRIG_PLUS                1086
#define IDC_GRAPH_TAU_E                 1087
#define IDC_OS_TRIG_MINUS               1088
#define IDC_GRAPH_TAU_1                 1089
#define IDC_OS_TRIG_AUTO                1090
#define IDC_GRAPH_TAU_2                 1091
#define IDC_GRAPH_SPECTROGRAM           1092
#define IDC_OS_TRIG_SINGLE              1093
#define IDC_OS_TRIG_LEVEL               1094
#define IDC_OS_TRIG_LEVEL2              1095
#define IDC_OS_LEVEL_L                  1096
#define IDC_OS_REVERSE_L                1097
#define IDC_OS_LEVEL_L2                 1098
#define IDC_OS_XY                       1099
#define IDC_OS_POS_L                    1100
#define IDC_TAUE_ORIGIN                 1101
#define IDC_OS_TRIG_RESET               1102
#define IDC_TAU1_A                      1103
#define IDC_OS_POS_L2                   1104
#define IDC_TAU1_B                      1105
#define IDC_OS_LEVEL_AUTO               1106
#define IDC_TAU1_A2                     1107
#define IDC_OS_TRIG_FREE                1108
#define IDC_OS_TRIG_POS                 1109
#define IDC_OS_LEVEL_R                  1110
#define IDC_OS_REVERSE_R                1111
#define IDC_OS_LEVEL_R2                 1112
#define IDC_OS_POS_R                    1113
#define IDC_OS_POS_R2                   1114
#define IDC_OS_TRIG_HIGHCUT             1115
#define IDC_OS_TRIG_LOWCUT              1116
#define IDC_OS_TRIG_DISP                1117
#define IDC_OS_POS_CENTER               1118
#define IDC_OS_POS_ALT                  1119
#define IDC_OS_DELAY_RANGE              1120
#define IDC_OS_MESSAGE                  1121
#define IDC_OS_CALIBRATION              1122
#define IDC_SG_DSLIDER                  1123
#define IDC_SG_DLEVEL                   1124
#define IDC_FFT_CF_AUTO                 1125
#define IDC_FFT_CF_LATERAL              1126
#define IDC_FFT_CALIBRATION             1127
#define IDC_MEASURENUMSPIN              1128
#define IDC_FOLDER_LIST                 1129
#define IDC_SCROLL_V                    1130
#define IDC_SAMPLING                    1131
#define IDC_MEASURE_TIME                1132
#define IDC_MEASURE_NUM                 1133
#define IDC_ZOOM_V                      1134
#define IDC_CHANNEL                     1135
#define IDC_REGIST                      1136
#define IDC_BIT                         1137
#define IDC_CHANGE                      1138
#define IDC_NAME                        1139
#define IDC_TIME                        1140
#define IDC_PLACE                       1141
#define IDC_DATE                        1142
#define IDC_MR_SAMPLING                 1143
#define IDC_TITLE                       1144
#define IDC_MR_MTIME                    1145
#define IDC_COMMENT                     1146
#define IDC_MR_MNUM                     1147
#define IDC_MR_BIT                      1148
#define IDC_DATA_TITLE                  1149
#define IDC_MR_CHANNEL                  1150
#define IDC_DATA_COMMENT                1151
#define IDC_MR_TIME                     1152
#define IDC_DATA_LIST                   1153
#define IDC_FOLER_TITLE                 1154
#define IDC_FOLDER_NAME                 1155
#define IDC_FOLDER_PLACE                1156
#define IDC_FOLDER_COMMENT              1157
#define IDC_FOLDER_DATE                 1158
#define IDC_WAVE_IN_MSEQ                1159
#define IDC_WAVE_IR                     1160
#define IDC_WAVE_OUT                    1161
#define IDC_WAVE_OUT_MSRQ               1162
#define IDC_IFA_SET                     1163
#define IDC_IFA_MESSAGE                 1164
#define IDC_IFA_SAVE                    1165
#define IDC_IFA_CANCEL                  1166
#define IDC_IMPALSE                     1167
#define IDC_SAVE                        1168
#define IDC_IR_LIST                     1169
#define IDC_FREQ                        1170
#define IDC_SET                         1171
#define IDC_START_POS                   1172
#define IDC_END_POS                     1173
#define IDC_MAX_ADJ_LEVEL               1174
#define IDC_PHASE_ADJ                   1175
#define IDC_SCALE                       1176
#define IDC_MICCAL_LIST                 1177
#define IDC_MICINFO                     1178
#define IDC_MICAMPINFO                  1179
#define IDC_FREQ_LIST                   1180
#define IDC_LEVEL                       1181
#define IDC_FREQ_RESPONSE               1182
#define IDC_READ                        1183
#define IDC_RESET                       1184
#define IDC_SIGNAL_OUT                  1185
#define IDC_INPUT_LEVEL                 1186
#define IDC_PRESET_LIST                 1187
#define IDC_FFT_PEAK_LEVEL              1188
#define IDC_FFT_PEAK_FREQ               1189
#define IDC_SAMPLING_RATE               1190
#define IDC_CHANNEL_MONO                1191
#define IDC_CHANNEL_STEREO              1192
#define IDC_INTEGRATION_TIME            1193
#define IDC_GRAPH_ACF                   1194
#define IDC_CALC_CYCLE                  1195
#define IDC_FILE_WAVE                   1196
#define IDC_GRAPH_WAVE                  1197
#define IDC_FILE_TEXT                   1198
#define IDC_MAX_TAU                     1199
#define IDC_TIME_DATA_NUM               1200
#define IDC_TIME_FWD                    1201
#define IDC_TIME_BWD                    1202
#define IDC_TIME_DATA_NUM_SPIN          1203
#define IDC_DATA_TIME                   1204
#define IDC_GRAPH_NORM                  1205
#define IDC_SCALE_LEVEL                 1206
#define IDC_MEASURE_TIME_SPIN           1207
#define IDC_FILE_LOAD                   1208
#define IDC_FILE_SAVE                   1209
#define IDC_SCALE_LINER                 1210
#define IDC_SCALE_LOG                   1211
#define IDC_SCALE_ABS                   1212
#define IDC_FREQ_FILTER                 1213
#define IDC_REDRAW                      1214
#define IDC_LEVEL_BAR                   1215
#define IDC_FILTER                      1216
#define IDC_ASSIST                      1217
#define IDC_DISTANCE                    1218
#define IDC_RESULT2                     1219
#define IDC_RESULT1                     1220
#define IDC_RESULT3                     1221
#define IDC_LEVEL_WND                   1222
#define IDC_MEASURING_TIME              1223
#define IDC_SN_RATIO                    1224
#define IDC_POSITION_RIGHT              1225
#define IDC_POSITION_LEFT               1226
#define IDC_DEVIATION                   1227
#define IDC_SWITCH1                     1228
#define IDC_SWITCH2                     1229
#define IDC_SWITCH3                     1230
#define IDC_AUTO_LEVEL                  1231
#define IDC_CUT                         1232
#define IDC_REPLAY                      1233
#define IDC_SELECT_START                1234
#define IDC_SELECT_END                  1235
#define IDC_SELECT_ALL                  1236
#define IDC_SELECT_TIME                 1237
#define IDC_SEPARATOR                   1238
#define IDC_CHANNEL_RCH                 1239
#define IDC_CHANNEL_LCH                 1240
#define IDC_WAVE_FILE                   1241
#define IDC_IMPORT_DATA                 1242
#define IDC_SFREQ_L                     1243
#define IDC_EFREQ_L                     1244
#define IDC_PLAYBACK                    1245
#define IDC_PRODUCT                     1246
#define IDC_COPYRIGHT                   1247
#define IDC_RL_SPLIT                    1248
#define IDC_FFT_CF_ZOOM                 1249
#define IDC_SCROLL_H                    1250
#define IDC_AUTO_RETRY                  1251
#define IDC_FFT_TIME_RES                1252
#define IDC_FFT_PEAK_TIME               1253
#define IDC_FFT_PEAK_RESET              1254
#define IDC_FFT_PEAK_AUTO               1255
#define IDC_FFT_PEAK_MANUAL             1256
#define IDC_FFT_TIME                    1257
#define IDC_SG_TIME                     1258
#define IDC_FFT_TIME_RES2               1259
#define IDC_TSP_METHOD                  1260
#define IDC_MSEQ_METHOD                 1261
#define IDC_FFT_AVERAGE                 1262
#define IDC_FFT_SMOOTHING               1263
#define IDC_PRODUCT_URL                 1264
#define IDC_OS_OVERLAY                  1265
#define IDC_COMPANY_URL                 1266
#define IDC_FFT_OCT_BAND                1267
#define IDC_EMAIL_ADDR                  1268
#define IDC_FFT_TIME_RANGE              1269
#define IDC_FREQ_EDIT                   1273
#define IDC_DST_TAB                     1274
#define IDC_LEVEL_EDIT                  1275
#define IDC_MAX_HxxxONICS               1276
#define IDC_RIGHT_THD                   1277
#define IDC_GUARD_TIME                  1278
#define IDC_FREQ_POINT                  1279
#define IDC_Hxxx_GRAPH                  1280
#define IDC_FREQ_SLIDER                 1281
#define IDC_LEVEL_SLIDER                1282
#define IDC_LEFT_THD                    1283
#define IDC_RA_SG                       1284
#define IDC_RA_FFT                      1285
#define IDC_RA_OS                       1286
#define IDC_RA_INPUT_DEVICE             1287
#define IDC_RA_OUTPUT_DEVICE            1288
#define IDC_RA_INPUT_SELECT             1289
#define IDC_RA_INPUT_VOLUME             1290
#define IDC_RA_DISP_LEVEL               1291
#define IDC_RA_FRE                      1292
#define IDC_RA_INPUT_LEVEL              1293
#define IDC_RA_OUTPUT_LEVEL             1294
#define IDC_RA_IMP                      1295
#define IDC_RA_DST                      1296
#define IDC_SCALE_MAX                   1297
#define IDC_SCALE_DB                    1298
#define IDC_SCALE_MIN                   1299
#define IDC_SCALE_PERCENT               1300
#define IDC_ELP_TIME                    1301
#define IDC_LEFT_UNIT                   1302
#define IDC_RIGHT_UNIT                  1303
#define IDC_FREQ_END                    1304
#define IDC_FREQ_START                  1305
#define IDC_FREQ_CURRENT                1306
#define IDC_FREQ_SPLINE                 1307
#define IDC_LEVEL_START                 1308
#define IDC_LEVEL_END                   1309
#define IDC_LEVEL_POINT                 1310
#define IDC_LEVEL_CURRENT               1311
#define IDC_LEVEL_SPLINE                1312
#define IDC_AVERAGE                     1313
#define IDC_RECORD                      1314
#define IDC_PLAY                        1315
#define IDC_RECORD_TIME                 1316
#define IDC_RA_REC                      1317
#define IDC_xxxx_STORE                  1318
#define IDC_RA_AUTOREC                  1318
#define IDC_DATA_RECORD                 1319
#define IDC_TIMING_CYCLE                1320
#define IDC_TIMING_MANUAL               1321
#define IDC_TIMING_INTERVAL             1322
#define IDC_TIMING_RECORD               1323
#define IDC_DELETE_DATA                 1324
#define IDC_TIMING_SPIN                 1325
#define IDC_DELETE_AT_START             1326
#define IDC_ALWAYS_NEW_DATA             1327
#define IDC_SCREEN_SHOT                 1328
#define IDC_FREQ_RANGE                  1329
#define IDC_WAVE_FORM                   1330
#define IDC_PHASE_SLIDER                1331
#define IDC_PHASE_VALUE                 1332
#define IDC_PRESET1                     1333
#define IDC_PRESET2                     1334
#define IDC_PRESET3                     1335
#define IDC_PRESET4                     1336
#define IDC_PRESET                      1337
#define IDC_PHASE0                      1338
#define IDC_TIME_SLIDER                 1339
#define IDC_TIME_VALUE                  1340
#define IDC_TIME0                       1341
#define IDC_BROWN_NOISE                 1342
#define IDC_DEFAULT                     1343
#define IDC_KEYBOARD                    1344
#define IDC_OCTAVE0                     1345
#define IDC_OCTAVE1                     1346
#define IDC_OCTAVE2                     1347
#define IDC_OCTAVE3                     1348
#define IDC_OCTAVE4                     1349
#define IDC_OCTAVE5                     1350
#define IDC_OCTAVE6                     1351
#define IDC_OCTAVE7                     1352
#define IDC_REFERENCE_PITCH             1353
#define IDC_OCTAVE8                     1354
#define IDC_SCALE_C                     1355
#define IDC_SCALE_CS                    1356
#define IDC_SCALE_D                     1357
#define IDC_SCALE_DS                    1358
#define IDC_SCALE_E                     1359
#define IDC_SCALE_F                     1360
#define IDC_SCALE_FS                    1361
#define IDC_SCALE_G                     1362
#define IDC_SCALE_GS                    1363
#define IDC_SCALE_A                     1364
#define IDC_SCALE_AS                    1365
#define IDC_SCALE_B                     1366
#define IDC_SYNTH_FREQ                  1367
#define IDC_COMP_LEVEL_1                1368
#define IDC_COMP_LEVEL_2                1369
#define IDC_COMP_LEVEL_3                1370
#define IDC_COMP_LEVEL_4                1371
#define IDC_COMP_LEVEL_5                1372
#define IDC_COMP_LEVEL_6                1373
#define IDC_COMP_LEVEL_7                1374
#define IDC_COMP_LEVEL_8                1375
#define IDC_COMP_FREQ_1                 1376
#define IDC_COMP_FREQ_2                 1377
#define IDC_COMP_FREQ_3                 1378
#define IDC_COMP_FREQ_4                 1379
#define IDC_COMP_FREQ_5                 1380
#define IDC_COMP_FREQ_6                 1381
#define IDC_COMP_FREQ_7                 1382
#define IDC_COMP_FREQ_8                 1383
#define IDC_LEVEL_SLIDER_1              1384
#define IDC_LEVEL_SLIDER_2              1385
#define IDC_LEVEL_SLIDER_3              1386
#define IDC_LEVEL_SLIDER_4              1387
#define IDC_LEVEL_SLIDER_5              1388
#define IDC_LEVEL_SLIDER_6              1389
#define IDC_LEVEL_SLIDER_7              1390
#define IDC_LEVEL_SLIDER_8              1391
#define IDC_PLAY_MODE                   1392
#define IDC_FONT_SIZE_SG                1393
#define IDC_FONT_SIZE_FFT               1394
#define IDC_FONT_SIZE_OS                1395
#define IDC_FONT_SIZE_DST               1396
#define IDC_FONT_SIZE_IMP               1397
#define IDC_FONT_SIZE_ACF               1398
#define IDC_PRIORITY_INPUT              1399
#define IDC_PRIORITY_OUTPUT             1400
#define IDC_FFT_OCT_BAND_GB             1401
#define IDC_FFT_TIME_RANGE_GB           1402
#define IDC_FFT_TIME_DATA_NUM_GB        1403
#define IDC_FFT_COLOR_GB                1404
#define IDC_FFT_COLOR                   1405
#define IDC_FFT_GRAY                    1406
#define IDC_MAKE_SHORTCUT               1407
#define IDC_FFT_CHANNEL                 1408
#define IDC_OS_ZERO_LEVEL               1409
#define IDC_OS_TIME                     1410
#define IDC_OS_CHANNEL                  1411
#define IDC_WAVE_WND                    1412
#define IDC_WAVEFORM1                   1413
#define IDC_WAVEFORM2                   1414
#define IDC_WAVEFORM3                   1415
#define IDC_WAVEFORM4                   1416
#define IDC_WAVEFORM5                   1417
#define IDC_EDIT                        1418
#define IDC_SFREQ                       1419
#define IDC_EFREQ                       1420
#define IDC_POS_X                       1421
#define IDC_POS_Y                       1422
#define IDC_VERTEX_ADD                  1423
#define IDC_VERTEX_MOVE                 1424
#define IDC_VERTEX_SEL                  1425
#define IDC_VERTEX_DELETE               1426
#define IDC_EDIT_SCROLL                 1427
#define IDC_SCROLL                      1428
#define IDC_SMOOTHING                   1429
#define IDC_ALL_CLEAR                   1430
#define ID_OK                           1431
#define IDC_MICCAL_TAB                  1432
#define IDC_COMMON_RL                   1433
#define IDC_SEPARATE_RL                 1434
#define IDC_TIME_RANGE                  1435
#define IDC_START_LEVEL                 1436
#define IDC_END_LEVEL                   1437
#define IDC_TIME_VALUE_SPIN             1438
#define IDC_PULSE_NUM_SPIN              1439
#define IDC_PULSE_CYCLE_SPIN            1440
#define IDC_FREQ_L_SPIN                 1441
#define IDC_FREQ_R_SPIN                 1442
#define IDC_REFERENCE_PITCH_SPIN        1443
#define IDC_SYNTH_FREQ_SPIN             1444
#define IDC_EFREQ_SPIN                  1445
#define IDC_FFT_AUTO_STOP_SPIN          1446
#define IDC_FFT_AUTO_STOP               1447
#define IDC_FFT_ZOOM_SCALE              1448
#define IDC_FONT_SIZE_FRE               1449
#define IDC_FRE_TAB                     1450
#define IDC_MAX_LEVEL                   1451
#define IDC_MIN_LEVEL                   1452
#define IDC_GRAPH                       1453
#define IDC_SWEEP_TIME                  1454
#define IDC_CSV_OUTPUT                  1455
#define IDC_RESOLUTION                  1456
#define IDC_FREQ_POINT_SPIN             1457
#define IDC_SWEEP_TIME_SPIN             1458
#define IDC_MAX_LEVEL_SPIN              1459
#define IDC_MIN_LEVEL_SPIN              1460
#define IDC_AVERAGING                   1461
#define IDC_CHK_MARKER                  1462
#define IDC_RADIO_FILTER_INPUT          1463
#define IDC_RADIO_FILTER_OUTPUT         1464
#define IDC_COMBO_FILTER_BAND           1465
#define IDC_EDIT_FILTER_RIPPLE1         1466
#define IDC_COMBO_FILTER_ORDER          1467
#define IDC_STATIC_FILTER_SPEC          1468
#define IDC_STATIC_FILTER_CURVE         1469
#define IDC_EDIT_CAL_VALUE              1470
#define IDC_COMBO_FILTER_SHAPE          1471
#define IDC_EDIT_FILTER_CUTOFF1         1472
#define IDC_EDIT_UNIT                   1473
#define IDC_EDIT_FILTER_CUTOFF2         1474
#define IDC_RADIO_EFECTIVE              1475
#define IDC_RADIO_PEAKTOPEAK            1476
#define IDC_BUTTON_DISABLE              1477
#define IDC_COMBO_HD                    1478
#define IDC_STATIC_SEPARATOR            1479
#define IDC_SEPARATOR_LINE              1480
#define IDC_TAB_WAVE_EDIT               1481
#define IDC_EDIT_MOD_AMP                1482
#define IDC_SLIDER_MOD_AMP              1483
#define IDC_BTN_TEST                    1484
#define IDC_EDIT_MOD_FREQ               1485
#define IDC_SLIDER_MOD_FREQ             1486
#define IDC_EDIT_FEEDBACK               1487
#define IDC_SLIDER_FEEDBACK             1488
#define IDC_FRE_MESSAGE                 1489
#define IDC_CAL_MESSAGE                 1490
#define IDC_SET_CALIBRATION             1491
#define IDC_ADD_DATA_HOLD               1492
#define IDC_DEL_DATA_HOLD               1493
#define IDC_INPUT_24BIT                 1494
#define IDC_INPUT_16BIT                 1495
#define IDC_OUTPUT_24BIT                1496
#define IDC_OUTPUT_16BIT                1497
#define IDC_LAUNCH_SA                   1498
#define IDC_EDIT_COMMENT                1499
#define IDC_LIST_BACKUP                 1500
#define IDC_DELETE_BACKUP               1501
#define IDC_CALC_CONDITIONS             1502
#define IDC_ACF_REALTIME_GRAPH          1503
#define IDC_SPG_MAX_LEVEL               1504
#define IDC_SPG_MIN_LEVEL               1505
#define IDC_SPG_LOG_SCALE               1506
#define IDC_SPG_LINEAR_SCALE            1507
#define IDC_TAUE_MAX_TIME               1508
#define IDC_TAUE_MIN_TIME               1509
#define IDC_TAUE_LOG_SCALE              1510
#define IDC_TAUE_LINEAR_SCALE           1511
#define IDC_TAUE_FIXED_SCALE            1513
#define IDC_EDIT_SAVE_FOLDER            1514
#define IDC_CHECK_INPUT_DATA            1515
#define IDC_BUTTON_REFERENCE            1516
#define IDC_CHECK_INPUT_DATA2           1517
#define IDC_CHECK_OUTPUT_DATA           1517
#define IDC_EDIT1                       1518
#define IDC_EDIT_OFFSET_TIME            1518
#define IDS_ABOUTBOX                    3001
#define IDS_TONE                        3002
#define IDS_NOISE                       3003
#define IDS_SWEEP                       3004
#define IDS_PULSE                       3005
#define IDS_START                       3006
#define IDS_STOP                        3007
#define IDS_SPECTRUM                    3008
#define IDS_OCTAVE                      3009
#define IDS_WATERFALL                   3010
#define IDS_CORRELATION                 3011
#define IDS_PHASE2                      3012
#define IDS_CPUOVERLOAD                 3013
#define IDS_ACF                         3014
#define IDS_TITLE                       3015
#define IDS_COMMENT                     3016
#define IDS_SAMPLING                    3017
#define IDS_LEFTCHANNEL                 3018
#define IDS_RIGHTCHANNEL                3019
#define IDS_NONE_HOSEI                  3020
#define IDS_MEASURING                   3021
#define IDS_RETRY                       3022
#define IDS_MICINFO                     3023
#define IDS_MICAMPINFO                  3024
#define IDS_INFINITE                    3025
#define IDS_ALL                         3026
#define IDS_INPUT_SELECT                3027
#define IDS_INPUT_FILE                  3028
#define IDS_MANUAL                      3029
#define IDS_FREQ_SWEEP                  3030
#define IDS_LEVEL_SWEEP                 3031
#define IDS_DISTORTION                  3032
#define IDS_HxxxONICS                   3033
#define IDS_ONLINE_MANUAL_CMD           3034
#define IDS_TECHNICAL_SUPPORT_CMD       3035
#define IDS_DOCUMENT_QA_CMD             3036
#define IDS_ERR_MEMORYALLOC             3037
#define IDS_ERR_WRITEWAVEFILE           3038
#define IDS_ERR_READWAVEFILE            3039
#define IDS_ERR_WRITEIRDATA             3040
#define IDS_ERR_READIRDATA              3041
#define IDS_MSG_SAVEIR                  3042
#define IDS_MSG_SOUNDINOUT              3043
#define IDS_ERR_TITLE                   3044
#define IDS_MSG_TITLE                   3045
#define IDS_MSG_CHANGEDATA              3046
#define IDS_ERR_WRITEDATA               3047
#define IDS_MSG_SELECTFOLDER            3048
#define IDS_MSG_MAKEFOLDER              3049
#define IDS_MSG_SELECTDATA              3050
#define IDS_MSG_DELTEMICCAL             3051
#define IDS_MSG_SAVEMICCAL              3052
#define IDS_MSG_SELECTMICCAL            3053
#define IDS_MSG_CHANGEMICCAL            3054
#define IDS_MSG_INPUTMICINFO            3055
#define IDS_ERR_MIXER                   3056
#define IDS_MSG_SELECTITEM              3057
#define IDS_MSG_CHANGEFOLDER            3058
#define IDS_MSG_UNDER0FREQ              3059
#define IDS_ERR_OPENOUTPUTFILE          3060
#define IDS_MSG_DELETESELECTDATA        3061
#define IDS_MSG_CHANGESELECTDATA        3062
#define IDS_MSG_SAVESELECTITEM          3063
#define IDS_MSG_DELETESELECTITEM        3064
#define IDS_ERR_READDATA                3065
#define IDS_MSG_SAVEDATA                3066
#define IDS_MSG_SAMPLINGRATE            3067
#define IDS_MSG_INPUTNDATA              3068
#define IDS_ERR_RUNNINGSTEP             3069
#define IDS_DATE_FORMAT                 3070
#define IDS_TIME_FORMAT                 3071
#define IDS_SCALE                       3072
#define IDS_SYNTH                       3073
#define IDS_SINUSOIDAL                  3074
#define IDS_TRIANGULAR                  3075
#define IDS_SQUARE                      3076
#define IDS_SAWTOOTH                    3077
#define IDS_SETTING                     3078
#define IDS_SPECTROGRAM                 3079
#define IDS_MSG_MAKE_SHORTCUT           3080
#define IDS_MONO                        3081
#define IDS_STEREO                      3082
#define IDS_RIGHT_AND_LEFT              3083
#define IDS_LEFT_ONLY                   3084
#define IDS_RIGHT_ONLY                  3085
#define IDS_DIFFERENCE                  3086
#define IDS_WAVE                        3087
#define IDS_WAVEFORM                    3088
#define IDS_COHERENCE                   3089
#define IDS_CROSS_SPECTRUM              3090
#define IDS_CEPSTRUM                    3091
#define IDS_COHERENCE2                  3092
#define IDS_SPOT_FREQ                   3093
#define IDS_PINK_NOISE                  3094
#define IDS_PDF_FILE                    3095
#define IDS_STATUS_STOP                 3096
#define IDS_STATUS_RUNNING              3097
#define IDS_MANUAL_EDIT                 3098
#define IDS_FM_SYNTH                    3099
#define IDS_INPUT                       3100
#define IDS_OUTPUT                      3101
#define IDS_RECORDING                   3102
#define IDS_PLAYING                     3103
#define IDS_RECORDED                    3104
#define IDS_NOT_RECORDED                3105
#define IDS_MEASUREMENT_DATA            3106
#define IDS_BACKUP_TIME                 3107
#define IDS_BACKUP_COMMENT              3108
#define IDS_BACKUP_DATA                 3109
#define IDS_RESTORE_DATA                3110
#define IDS_DELETE_BACKUP_DATA          3111
#define IDS_SELECT_DELETE_DATA          3112
#define IDS_SELECT_RESTORE_DATA         3113
#define IDS_BACKUP_END                  3114
#define IDS_RESTORE_END                 3115
#define IDS_FONT_ENLARGE                3116
#define IDS_FONT_REDUCE                 3117
#define IDS_INITIAL_PRESET              3118
#define IDS_NO_AUTO_REC_FOLDER          3119
#define IDS_SAVE_FOLDER                 3120
#define IDS_HELP_FILE                   9000
#define IDM_ONLINE_MANUAL               20001
#define IDM_TECHNICAL_SUPPORT           20002
#define IDM_DOCUMENT_QA                 20003
#define IDM_RA_SG                       20004
#define IDM_RA_FFT                      20005
#define IDM_RA_OS                       20006
#define IDM_RA_IMP                      20007
#define IDM_RA_DST                      20008
#define IDM_RA_ACF                      20009
#define IDM_RA_REC                      20010
#define IDM_RA_PRESET                   20011
#define IDM_RA_TIME                     20012
#define IDM_ZOOM_FULL_H                 20013
#define IDM_ZOOM_FULL_V                 20014
#define IDM_ZOOM_IN_H                   20015
#define IDM_ZOOM_IN_V                   20016
#define IDM_ZOOM_OUT_V                  20017
#define IDM_ZOOM_OUT_H                  20018
#define IDM_README                      20019
#define IDM_xxxx_STORE                  20020
#define IDM_LICENSE_REGIST              20021
#define IDM_CLOSE                       20022
#define IDM_SIZE_12_POINT               20023
#define IDM_SIZE_11_POINT               20024
#define IDM_SIZE_10_POINT               20025
#define IDM_SIZE_9_POINT                20026
#define IDM_SIZE_8_POINT                20027
#define IDM_FORMAT_DATE                 20028
#define IDM_FORMAT_TIME                 20029
#define IDM_FORMAT_DATE_TIME            20030
#define IDM_TRANSPARENT                 20031
#define IDM_TRANSPARENCY_0              20032
#define IDM_TRANSPARENCY_1              20033
#define IDM_TRANSPARENCY_2              20034
#define IDM_TRANSPARENCY_3              20035
#define IDM_TRANSPARENCY_4              20036
#define IDM_RA_FRE                      20037
#define IDM_SETTING                     20038
#define IDM_HELP_FILE                   20039
#define IDM_PDF_FILE                    20040
#define IDM_RA_FLT                      20041
#define IDM_RA_FILTER                   20042
#define IDM_POPUP_FILE_SAVE             20043
#define IDM_DELETE                      20044
#define IDM_ADD                         20045
#define IDM_BACKUP                      20046
#define IDM_DATA_BACKUP                 20047
#define IDM_DATA_RESTORE                20048
#define IDM_START                       20049
#define IDM_STOP                        20050
#define IDM_CALC_CONDITIONS             20051
#define ID_20052                        20052
#define IDM_                            20053
#define IDM_TRANSFER_MMLIB              20054
#define ID_BUTTON20055                  20055

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        268
#define _APS_NEXT_COMMAND_VALUE         20056
#define _APS_NEXT_CONTROL_VALUE         1519
#define _APS_NEXT_SYMED_VALUE           10000
#endif
#endif
