/************************************************************************
 *									*
 *		“‡Œõ”g•\¦‘•’u@‚r^‚f@‚b‚o‚tƒvƒƒOƒ‰ƒ€		*
 *									*
 *		–¼Ì		: ‚o^‚`ƒrƒbƒg				*
 *		ƒtƒ@ƒCƒ‹–¼	: pa_bit.h				*
 *									*
 ************************************************************************/

#define	PA_T000		0
#define	PA_T001		1
#define	PA_T002		2
#define	PA_T003		3
#define	PA_T004A	4
#define	PA_T004B	5
#define	PA_T004C	6
/*	7`15 —\”õ	*/
#define	PA_K050A	16
#define	PA_K050B	17
#define	PA_K050C	18
#define	PA_K050D	19
#define	PA_K050E	20
#define	PA_K050F	21
#define	PA_K050G	22
#define	PA_K050H	23
#define	PA_K050I	24
#define	PA_K050J	25
#define	PA_K050K	26
#define	PA_K050L	27
#define	PA_K050M	28
#define	PA_K050N	29
#define	PA_K050O	30
#define	PA_K050P	31
#define	PA_K050Q	32
#define	PA_K050R	33
/*	34`47 —\”õ	*/
#define	PA_K051A	48
#define	PA_K051B	49
#define	PA_K051C	50
#define	PA_K051D	51
#define	PA_K051E	52
#define	PA_K051F	53
#define	PA_K051G	54
#define	PA_K051H	55
#define	PA_K051I	56
#define	PA_K051J	57
#define	PA_K051K	58
#define	PA_K051L	59
#define	PA_K051M	60
#define	PA_K051N	61
#define	PA_K051O	62
#define	PA_K051P	63
#define	PA_K051Q	64
#define	PA_K051R	65
/*	66`79 —\”õ	*/
#define	PA_K053A	80
#define	PA_K053B	81
#define	PA_K053C	82
#define	PA_K053D	83
#define	PA_K053E	84
#define	PA_K053F	85
#define	PA_K053G	86
#define	PA_K053H	87
#define	PA_K053I	88
#define	PA_K053J	89
#define	PA_K053K	90
#define	PA_K053L	91
#define	PA_K053M	92
#define	PA_K053N	93
#define	PA_K053O	94
#define	PA_K053P	95
#define	PA_K053Q	96
#define	PA_K053R	97
/*	98`111 —\”õ	*/
#define	PA_K052A	112
#define	PA_K052B	113
#define	PA_K052C	114
#define	PA_K052D	115
#define	PA_K052E	116
#define	PA_K052F	117
#define	PA_K052G	118
#define	PA_K052H	119
#define	PA_K052I	120
#define	PA_K052J	121
#define	PA_K052K	122
#define	PA_K052L	123
#define	PA_K052M	124
#define	PA_K052N	125
#define	PA_K052O	126
#define	PA_K052P	127
#define	PA_K052Q	128
#define	PA_K052R	129
/*	130`255 —\”õ	*/
#define	PA_KD19		176
#define	PA_KD18		177
#define	PA_KD17		178
#define	PA_KD16A	179
#define	PA_KD16B	180
#define	PA_KD16C	181
#define	PA_KD15A	182
#define	PA_KD15B	183
#define	PA_KD15C	184
#define	PA_KD12A	185
#define	PA_KD12B	186
#define	PA_KD11A	187
#define	PA_KD11B	188
#define	PA_KD11C	189
#define	PA_KD10		190
/*	191 —\”õ	*/
#define	PA_KD140	192
#define	PA_KD141	193
#define	PA_KD142	194
#define	PA_KD143	195
#define	PA_KD144	196
/*	197`199 —\”õ	*/
#define	PA_KD13A0	200
#define	PA_KD13A1	201
#define	PA_KD13A2	202
/*	203 —\”õ	*/
#define	PA_KD13B0	204
#define	PA_KD13B1	205
#define	PA_KD13B2	206
/*	207`223 —\”õ	*/
#define	PA_K020A	224
#define	PA_K020B	225
#define	PA_K020C	226
#define	PA_K020D	227
#define	PA_K021A0	228
#define	PA_K021A1	229
#define	PA_K021A2	230
#define	PA_K021B	231
#define	PA_K022A	232
#define	PA_K022B	233
#define	PA_K027A	234
#define	PA_K027B	235
#define	PA_K028A	236
#define	PA_K028B	237
#define	PA_K009		238
#define	PA_K004B0	239
#define	PA_K004B1	240
#define	PA_K004B2	241
#define	PA_K003		242
#define	PA_K002B	243
#define	PA_K001		244
/*	245`255 —\”õ	*/
#define	PA_K0300	256
/*	`355‚Ü‚ÅáŠQ•¨ƒVƒ“ƒ{ƒ‹(GREEN)	*/
/*	356`367 —\”õ	*/
#define	PA_K024A	368
#define	PA_K024B	369
#define	PA_K022C	370
#define	PA_K021C	371
#define	PA_K004A0	372
#define	PA_K004A1	373
#define	PA_K004A2	374
/*	375`383 —\”õ	*/
#define	PA_K0100	384
/*	`483‚Ü‚ÅáŠQ•¨ƒVƒ“ƒ{ƒ‹(YELLOW)	*/
/*	484`495 —\”õ	*/
#define	PA_K026		496
#define	PA_K025A	497
#define	PA_K025B	498
#define	PA_K025C	499
#define	PA_K025D	500
#define	PA_K023A	501
#define	PA_K023B	502
#define	PA_K007		503
#define	PA_K006		504
#define	PA_K008		505
#define	PA_K005		506
#define	PA_K004C0	507
#define	PA_K004C1	508
#define	PA_K004C2	509
#define	PA_K002A	510
/*	511 —\”õ	*/
#define	PA_K0200	512
/*	`611‚Ü‚ÅáŠQ•¨ƒVƒ“ƒ{ƒ‹(RED)	*/
/*	612`623 —\”õ	*/
#define	PA_K044A	624
#define	PA_K042A	625
#define	PA_K040A	626
#define	PA_K040B	627
#define	PA_K044B	628
#define	PA_K042B	629
#define	PA_K041A	630
#define	PA_K041B	631
/*	632`639 —\”õ	*/
#define	PA_K045A	640
#define	PA_K045B	641
#define	PA_K048A	642
#define	PA_K047A	643
#define	PA_K046A	644
#define	PA_K046B	645
#define	PA_K048B	646
#define	PA_K047B	647
/*	648`655 —\”õ	*/
#define	PA_KD43		656

#define	PA_KDOT00	1023
