/* ----- @(#)d3clky.h 1.2 88/05/10 15:22:26 ----- */

/*
		FILE.NAME	: d3clky.h 
		REMARKS		:	88.01.17	S.Takahashi
*/
#include	<stdio.h>
#include	"la_ws/include/d3libc.h"
/******************************************************************************/
/*	local defines							      */
/******************************************************************************/
#define		NOT_USE	0
#define 	USE	1
