
#define	MENU_MANUALWINDOWTITLE_NUM	4

extern	struct MENUCTRLDATA	Menu_ManualWindowTitle[MENU_MANUALWINDOWTITLE_NUM];

#define	MENU_MANUALWINDOWPOPUP_NUM	11

extern	struct MENUCTRLDATA	Menu_ManualWindowPopup[MENU_MANUALWINDOWPOPUP_NUM];

#define	MENU_MANUALWINDOWTEXT_NUM	11

extern	struct MENUCTRLDATA	Menu_ManualWindowText[MENU_MANUALWINDOWTEXT_NUM];

#define	MENU_MANUALWINDOWBAR_NUM	4

extern	struct MENUCTRLDATA	Menu_ManualWindowBar[MENU_MANUALWINDOWBAR_NUM];
