//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WorkScheduler.rc
//
#define IDC_BUTTON_PREVIEW              3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WORKSCHEDULER_DIALOG        102
#define IDR_MANUAL_FRAME                102
#define IDR_MAINFRAME                   128
#define IDD_START_MENU                  129
#define IDD_SET_CONDITIONS              130
#define IDD_AUTO_SCHEDULING             131
#define IDI_ICON_TRIA_CYAN              134
#define IDD_MANUAL_SCHEDULING           140
#define IDI_IDI_ICON_TRIA_YELLOW        141
#define IDR_MAIN_MENU                   142
#define IDR_MANUAL_POPUPMENU            143
#define IDD_MANUAL_MOVE                 144
#define IDD_MANUAL_BUNKATSU             145
#define IDD_SET_KITTING                 148
#define IDD_MANUAL_BAR                  156
#define IDD_MANUAL_VIEW_TYPE            157
#define IDB_BITMAP_VIEW_TYPE1           158
#define IDB_BITMAP_VIEW_TYPE2           159
#define IDB_BITMAP_VIEW_TYPE3           160
#define IDB_BITMAP_VIEW_TYPE4           161
#define IDD_LOGIN                       162
#define IDD_SEISAN_JOKEN1               163
#define IDD_SEISAN_JOKEN2               165
#define IDD_SAVE_PROJECT                167
#define IDD_SET_KYOTSU_KOTEI            168
#define IDR_KYOTSU_KOTEI                170
#define IDD_KTASHIKI_KISEI_MATRIX       171
#define IDC_CURSOR1                     172
#define IDD_MANUAL_SUBLINE              173
#define IDB_BITMAP_KYOTSU_KOTEI         174
#define IDD_MANUAL_EDIT                 175
#define IDB_BITMAP_POST_DRAG            176
#define IDD_MANUAL_DSTR                 178
#define IDD_FILE_EXPORT_DIALOG          179
#define IDD_MANUAL_KISHU_BAR            180
#define IDC_BUTTON_START                1000
#define IDC_BUTTON_SET_CONDITIONS       1001
#define IDC_BUTTON_AUTO_SCHEDULING      1002
#define IDC_BUTTON_EXIT                 1003
#define IDC_STATIC_STATUS               1004
#define IDC_BUTTON_MANUAL_SCHEDULING    1005
#define IDC_BUTTON_SET_SEISAN_JOKEN     1006
#define IDC_RADIO_KOJUN1                1007
#define IDC_SPREAD                      1008
#define IDC_RADIO_KOJUN2                1009
#define IDC_STATIC_CHILD_MENU           1011
#define IDC_BUTTON_READ_DATA            1012
#define IDC_BUTTON_SET_LINE_KISEI       1013
#define IDC_BUTTON_MANUAL               1014
#define IDC_BUTTON_DEBUG1               1015
#define IDC_BUTTON_SET_KATASHIKI_KISEI  1016
#define IDC_BUTTON_DEBUG2               1017
#define IDC_BUTTON_SET_KITTING          1018
#define IDC_BUTTON_SET_KYOTU_KOTEI      1019
#define IDC_COMBO_KISHU                 1024
#define IDC_COMBO_SAGYOSHA1             1026
#define IDC_STATIC010                   1026
#define IDC_STATIC012                   1028
#define IDC_COMBO_SAGYOSHA2             1029
#define IDC_STATIC014                   1030
#define IDC_STATIC015                   1031
#define IDC_BUTTON_SETTEI               1032
#define IDC_BUTTON_CALC                 1032
#define IDC_LIST1                       1033
#define IDC_STATIC019                   1033
#define IDC_LIST2                       1034
#define IDC_BUTTON_RIGHT_MOVE           1035
#define IDC_BUTTON_LEFT_MOVE            1036
#define IDC_STATIC_TOTAL_TIME1          1037
#define IDC_STATIC_TOTAL_TIME2          1038
#define IDC_COMBO_SAGYOSHA              1043
#define IDC_COMBO_KOTEI                 1044
#define IDC_COMBO_YOSO_SAGYOGUN         1045
#define IDC_STATIC_SUBLINE              1051
#define IDC_SPREAD_KOTEI                1057
#define IDC_SPREAD_YOSO_SAGYOGUN        1059
#define IDC_SPREAD_YOSO_SAGYO           1061
#define IDC_EDITEX                      1062
#define IDC_RADIO_GRAPH_KOTEI           1065
#define IDC_RADIO_GRAPH_YOSOSAGYOGUN    1066
#define IDC_RADIO_VIEW_TYPE1            1067
#define IDC_RADIO_VIEW_TYPE2            1068
#define IDC_RADIO_VIEW_TYPE3            1069
#define IDC_RADIO_VIEW_TYPE4            1070
#define IDC_COMBO_VIEW1                 1071
#define IDC_COMBO_VIEW2                 1072
#define IDC_EDIT_SHOKUBAN               1072
#define IDC_COMBO_VIEW3                 1073
#define IDC_RADIO_KOTEI                 1074
#define IDC_RADIO_YOSO_SAGYOGUN         1075
#define IDC_BUTTON_ZENSENTAKU           1076
#define IDC_BUTTON_ZENKAIJO             1077
#define IDC_BUTTON_NEXT                 1078
#define IDC_PROGRESS_BAR                1079
#define IDC_BUTTON_BACK                 1080
#define IDC_COMBO_YEAR                  1081
#define IDC_COMBO_MONTH                 1082
#define IDC_EDIT_KISHU1                 1083
#define IDC_EDIT_DAISU1                 1084
#define IDC_EDIT_KISHU2                 1085
#define IDC_EDIT_DAISU2                 1086
#define IDC_EDIT_KISHU3                 1087
#define IDC_EDIT_DAISU3                 1088
#define IDC_EDIT_KISHU4                 1089
#define IDC_EDIT_DAISU4                 1090
#define IDC_EDIT_KISHU5                 1091
#define IDC_EDIT_DAISU5                 1092
#define IDC_BUTTON_IKO_JOGEN            1093
#define IDC_BUTTON_IKO_KAGEN            1094
#define IDC_BUTTON_IKO_KINMU            1095
#define IDC_BUTTON_IKO_KYUSOKU          1096
#define IDC_BUTTON_IKO_KADO             1097
#define IDC_RADIO_MOKUHYO_TACT_YUSEN    1098
#define IDC_BUTTON_IKO_KOTAI            1099
#define IDC_RADIO_JIDO_KOTEI_YUSEN      1100
#define IDC_COMBO_KIJUN_KISHU           1101
#define IDC_EDIT_PROJECT_NAME           1103
#define IDC_STATIC_YEAR                 1104
#define IDC_STATIC_MONTH                1105
#define IDC_STATIC_SEISAN_DAISU         1106
#define IDC_COMBO_SUBLINE               1107
#define IDC_BUTTON_KITTING_TAISHO_BUHINHYO 1108
#define IDC_STATIC_KIT_NASHI_GOKEI_JIKAN 1109
#define IDC_EDIT_KIT_NASHI_GOKEI_JIKAN  1110
#define IDC_STATIC_KIT_ARI_GOKEI_JIKAN  1111
#define IDC_EDIT_KIT_ARI_GOKEI_JIKAN    1112
#define IDC_STATIC_KIT_SA_JIKAN         1113
#define IDC_EDIT_KIT_SA_JIKAN           1114
#define IDC_SPREAD_BUHIN                1115
#define IDC_CHECK_KATASHIKI_1           1116
#define IDC_CHECK_KATASHIKI_2           1117
#define IDC_CHECK_SUBLINE_1             1118
#define IDC_CHECK_KATASHIKI_3           1119
#define IDC_CHECK_SUBLINE_2             1120
#define IDC_CHECK_KATASHIKI_4           1121
#define IDC_CHECK_SUBLINE_3             1122
#define IDC_CHECK_KATASHIKI_5           1123
#define IDC_CHECK_SUBLINE_4             1124
#define IDC_CHECK_SUBLINE_5             1125
#define IDC_CHECK_SUBLINE_6             1126
#define IDC_CHECK_SUBLINE_7             1127
#define IDC_CHECK_SUBLINE_8             1128
#define IDC_CHECK_SUBLINE_9             1129
#define IDC_CHECK_SUBLINE_10            1130
#define IDC_CHECK_SUBLINE_11            1131
#define IDC_CHECK_SUBLINE_12            1132
#define IDC_CHECK_SUBLINE_13            1133
#define IDC_CHECK_SUBLINE_14            1134
#define IDC_CHECK_SUBLINE_15            1135
#define IDC_STATIC_VERSION              1136
#define IDC_EDIT_KISHU_NAME             1137
#define IDC_BUTTON_KOTEI_TSUIKA         1138
#define IDC_BUTTON_KOTEI_SAKUJO         1139
#define IDC_BUTTON_YOSO_SAGYOGUN_TSUIKA 1140
#define IDC_BUTTON_YOSO_SAGYOGUN_SAKUJO 1141
#define IDC_BUTTON_YOSO_SAGYO_TSUIKA    1142
#define IDC_BUTTON_YOSO_SAGYO_SAKUJO    1143
#define IDC_STATIC002                   1144
#define IDC_STATIC003                   1145
#define IDC_STATIC004                   1146
#define IDC_STATIC005                   1147
#define IDC_STATIC5                     1147
#define IDC_STATIC013                   1148
#define IDC_STATIC018                   1149
#define IDC_STATIC001                   1150
#define IDC_STATIC006                   1151
#define IDC_STATIC008                   1152
#define IDC_STATIC011                   1153
#define IDC_STATIC007                   1154
#define IDC_STATIC009                   1155
#define IDC_LIST001                     1156
#define IDC_LIST_BUHIN                  1157
#define IDC_LIST_KOTEI                  1158
#define IDC_LIST_YOSO_SAGYOGUN          1159
#define IDC_LIST_YOSO_SAGYO             1160
#define IDC_COMBOEX                     1161
#define IDC_EDIT001                     1162
#define IDC_EDIT002                     1163
#define IDC_EDIT003                     1164
#define IDC_EDIT004                     1165
#define IDC_EDIT005                     1166
#define IDC_EDIT006                     1167
#define IDC_EDIT007                     1168
#define IDC_EDIT008                     1169
#define IDC_EDIT009                     1170
#define IDC_EDIT010                     1171
#define IDC_EDIT011                     1172
#define IDC_EDIT012                     1173
#define IDC_CHECK_ZENKISHU              1174
#define IDC_CHECK_KAJUU_HEIKIN          1175
#define IDC_CHECK_KISHU_1               1176
#define IDC_CHECK_KISHU_2               1177
#define IDC_CHECK_KISHU_3               1178
#define IDC_CHECK_KISHU_4               1179
#define IDC_CHECK_KISHU_5               1180
#define IDC_CHECK_WARITUKE              1181
#define IDC_BACK_REF_KOTEI              1182
#define IDC_NEXT_REF_KOTEI              1183
#define IDS_MANUAL_VIEW_EDIT            5001
#define IDS_MANUAL_VIEW_LIST            5002
#define IDS_MANUAL_VIEW_INFO            5003
#define IDS_JAKU_HEIKIN                 5004
#define IDS_JIDO                        5005
#define IDS_HAN_JIDO                    5006
#define IDS_SEIRITSU                    5007
#define IDS_TORITSU                     5008
#define IDS_CHOKURITSU                  5009
#define IDS_JORYU                       5010
#define IDS_KARYU                       5011
#define IDS_MOKUHYO_TACT                5012
#define IDS_ERR_SYSTEM_INI              5013
#define IDS_ERR_SYSTEM_INI_ENG          5014
#define IDS_ERR_MESSAGE_FILE            5015
#define IDS_ERR_MESSAGE_FILE_ENG        5016
#define IDM_MANUAL_MOVE                 32773
#define IDM_MANUAL_BUNKATSU             32774
#define IDM_MANUAL_EDIT                 32776
#define IDM_FILE_EXPORT                 32781
#define IDM_VIEW_SLIM_GRAPH             32783
#define IDM_VIEW_SELECT_SUBLINE         32784
#define IDM_TOOL_KITTING_SET            32785
#define IDM_TOOL_KYOTSU_KOTEI           32788
#define IDM_HELP_VERSION                32790
#define IDM_MANUAL_COPY                 32792
#define IDM_MANUAL_PASTE                32793
#define IDM_MANUAL_SAGYOSHA_SAKUJO      32794
#define IDM_MANUAL_DSTR                 32795
#define IDM_WINDOW_VIEW_TYPE            32796
#define IDM_KYOTSU_KOTEI_ZEN_SETTEI     32797
#define IDM_KYOTSU_KOTEI_ZEN_KAIJO      32798
#define IDM_KYOTSU_KOTEI_KAIJO          32799
#define IDM_TOOL_LINE_KISEI             32800
#define IDM_TOOL_KATASHIKI_KISEI        32801
#define IDM_FILE_SAVE_AS                32803
#define IDM_FILE_SAVE                   32804
#define IDM_FILE_CLOSE                  32805
#define IDM_EDIT_UNDO                   32806
#define IDM_EDIT_REDO                   32807
#define IDM_WINDOW_SEIRETSU             32808
#define IDM_MANUAL_SAGYOSHA_MAE         32809
#define IDM_MANUAL_SAGYOSHA_USHIRO      32810

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        181
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1183
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
