
// ダイアログの設定
#define	MENU_SETKYOTSUKOTEIDLG_NUM	14

struct MENUCTRLDATA	Menu_SetKyotsuKoteiDlg[MENU_SETKYOTSUKOTEIDLG_NUM] = {
{	CTRL_TYPE_TITLE,		        0,	"D004006",	"T001001",		NULL,			NULL	},
{	CTRL_TYPE_STATIC,	IDC_STATIC002,	"D004006",	"S001002",		NULL,			NULL	},
{	CTRL_TYPE_STATIC,	IDC_STATIC003,	"D004006",	"S001003",		NULL,			NULL	},
{	CTRL_TYPE_LVIEW,	  IDC_LIST001,	"D004006",	"V001004",		NULL,			NULL	},
{	CTRL_TYPE_LVIEW,	  IDC_LIST001,	"D004006",	"V001005",		NULL,			NULL	},
{	CTRL_TYPE_LVIEW,	  IDC_LIST001,	"D004006",	"V001006",		NULL,			NULL	},
{	CTRL_TYPE_LVIEW,	  IDC_LIST001,	       "",	       "",		NULL,			NULL	},
{	CTRL_TYPE_LVIEW,	  IDC_LIST001,	       "",	       "",		NULL,			NULL	},
{	CTRL_TYPE_LVIEW,	  IDC_LIST001,	       "",	       "",		NULL,			NULL	},
{	CTRL_TYPE_LVIEW,	  IDC_LIST001,	       "",	       "",		NULL,			NULL	},
{	CTRL_TYPE_LVIEW,	  IDC_LIST001,	       "",	       "",		NULL,			NULL	},
{	CTRL_TYPE_BUTTON,	         IDOK,	"D004006",	"B001007",		NULL,			NULL	},
{	CTRL_TYPE_BUTTON,	     IDCANCEL,	"D004006",	"B001008",		NULL,			NULL	},
{	              -1,	            0,		   "",	       "",		NULL,			NULL	}
};

// ポップアップメニューの設定
#define	MENU_SETKYOTSUKOTEIPOPUP_NUM	4

struct MENUCTRLDATA	Menu_SetKyotsuKoteiPopup[MENU_SETKYOTSUKOTEIPOPUP_NUM] = {
{	CTRL_TYPE_POPUP,	IDM_KYOTSU_KOTEI_ZEN_SETTEI,	"P004007",	"M001001",		NULL,			NULL	},
{	CTRL_TYPE_POPUP,	 IDM_KYOTSU_KOTEI_ZEN_KAIJO,	"P004007",	"M001002",		NULL,			NULL	},
{	CTRL_TYPE_POPUP,	     IDM_KYOTSU_KOTEI_KAIJO,	"P004007",	"M001003",		NULL,			NULL	},
{	             -1,	                          0,		   "",	       "",		NULL,			NULL	}
};

#define LIST_SETKYOTSUKOTEIDLG_NUM	9

struct LIxxxTRLDATA List_SetKyotsuKoteiDlg[LIST_SETKYOTSUKOTEIDLG_NUM] = {
{	0,		3,		20,	LVCFMT_LEFT,	FALSE,	FALSE,	eITEMTYPE_STRING,		eINPUTTYPE_NOTEDIT,		"",		0,	0,	0	},
{	1,		4,		20,	LVCFMT_LEFT,	FALSE,	FALSE,	eITEMTYPE_STRING,		eINPUTTYPE_NOTEDIT,		"",		0,	0,	0	},
{	2,		5,		8,	LVCFMT_LEFT,	FALSE,	FALSE,	eITEMTYPE_STRING,		eINPUTTYPE_NOTEDIT,		"",		0,	0,	0	},
{	3,		6,		8,	LVCFMT_RIGHT,	FALSE,	FALSE,	eITEMTYPE_STRING,		eINPUTTYPE_COMBOBOX,	"",		0,	0,	0	},
{	4,		7,		8,	LVCFMT_RIGHT,	FALSE,	FALSE,	eITEMTYPE_STRING,		eINPUTTYPE_COMBOBOX,	"",		0,	0,	0	},
{	5,		8,		8,	LVCFMT_RIGHT,	FALSE,	FALSE,	eITEMTYPE_STRING,		eINPUTTYPE_COMBOBOX,	"",		0,	0,	0	},
{	6,		9,		8,	LVCFMT_RIGHT,	FALSE,	FALSE,	eITEMTYPE_STRING,		eINPUTTYPE_COMBOBOX,	"",		0,	0,	0	},
{	7,		10,		6,	LVCFMT_RIGHT,	FALSE,	FALSE,	eITEMTYPE_STRING,		eINPUTTYPE_COMBOBOX,	"",		0,	0,	0	},
{	-1,		-1,		0,	            0,	FALSE,	FALSE,	               0,						0,		"",		0,	0,	0	}
};
