//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MMLib.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MMLIBTYPE                   129
#define IDB_IMAGE_LIST_SMALL            130
#define IDD_LIBOPEN                     132
#define IDB_IMAGE_LIST_LARGE            132
#define IDD_LIBNEW                      133
#define IDD_FOLDER                      134
#define IDR_GFOLDER                     136
#define IDR_ROOT                        137
#define IDR_DATA                        138
#define IDR_PICT                        139
#define IDD_FOLDERNEW                   142
#define IDR_DFOLDER                     142
#define IDD_DATA                        143
#define IDR_FIND                        143
#define IDR_PICTFRAME                   144
#define IDD_FIND                        146
#define IDC_HANDOPEN                    148
#define IDC_HANDCLOSE                   149
#define IDD_DATA_LARGE                  152
#define IDD_OPT_TWAIN                   161
#define IDD_OPT_FONT                    162
#define IDD_AUTO_NUMBERING              163
#define IDD_OPT_ORDER                   164
#define IDD_BACKUP                      166
#define IDD_RESTORE                     167
#define IDD_OPT_FOLDER                  168
#define IDD_TRANS_REG                   170
#define IDD_PICT_ROTATE                 172
#define IDD_PASSWORD                    173
#define IDD_PERMISSION                  174
#define IDD_CHECK_PWD                   175
#define IDD_REF_NET                     176
#define IDD_INFO_VIEW                   177
#define IDR_TEXT                        178
#define IDD_TEXT                        179
#define IDR_INBOX                       179
#define IDR_VIEW                        180
#define IDD_MAKE_INDEX                  183
#define IDR_FINDFRAME                   184
#define IDD_MAIL_ATT                    186
#define IDD_OPT_IMAGE_EDITOR            187
#define IDC_SELECT_WINDOW               188
#define IDD_FIND_SIMPLE                 190
#define IDR_LIBRARY                     191
#define IDC_LOCAL                       1000
#define IDC_NETBIOS                     1001
#define IDC_TCPIP                       1002
#define IDC_SERVER_NAME                 1003
#define IDC_DIRECTORY                   1004
#define IDC_PICT_SCANNER                1004
#define IDC_LIBNAME                     1005
#define IDC_TITLE                       1005
#define IDC_CREATOR                     1006
#define IDC_PICT_FILE                   1007
#define IDC_CREATEDATE                  1007
#define IDC_REMARK                      1008
#define IDC_KEYWORD                     1009
#define IDC_FOLDERNAME                  1010
#define IDC_UPDATEDATE                  1010
#define IDC_SAVE                        1011
#define IDC_GROUP_FOLDER                1012
#define IDC_DATA_FOLDER                 1013
#define IDC_PICT_CAMERA                 1022
#define IDC_PICT_WIDTH                  1023
#define IDC_PICT_ROTATION               1024
#define IDC_PICT_HEIGHT                 1025
#define IDC_PICT_COLOR                  1026
#define IDC_PICT_DPI                    1027
#define IDC_PICT_PICTURE                1028
#define IDC_PICT_ERASE                  1029
#define IDC_LIBRARY                     1030
#define IDC_FIND_FOLDER                 1033
#define IDC_CACHE                       1036
#define IDC_CACHE_FOLDER                1037
#define IDC_CODE                        1039
#define IDC_CACHE_REFERENCE             1039
#define IDC_SELECT_DRIVER               1040
#define IDC_TWAIN_DRIVER                1042
#define IDC_REFERENCE                   1045
#define IDC_GETFINDNUM                  1046
#define IDC_FINDNUM                     1047
#define IDC_CREATE_DATE_FROM            1048
#define IDC_CREATE_DATE_TO              1049
#define IDC_UPDATE_DATE_FROM            1050
#define IDC_UPDATE_DATE_TO              1051
#define IDC_CREATE_DATE_BEFORE          1052
#define IDC_CONDITION_TAB               1053
#define IDC_UPDATE_DATE_BEFORE          1055
#define IDC_FRONT_MATCHING              1057
#define IDC_FULL_MATCHING               1058
#define IDC_WILDCARD                    1059
#define IDC_NOCASE                      1060
#define IDC_DATA                        1061
#define IDC_FOLDER                      1062
#define IDC_NORMAL_FONT                 1064
#define IDC_LARGE_FONT                  1065
#define IDC_VIEW_FONT_NAME              1069
#define IDC_AUTO_NUMBERING              1069
#define IDC_VIEW_FONT_SIZE              1070
#define IDC_AUTO_SAVE                   1070
#define IDC_VIEW_FONT_CHANGE            1071
#define IDC_STEP                        1074
#define IDC_ORDER_LIST                  1076
#define IDC_UP                          1077
#define IDC_DOWN                        1078
#define IDC_BACKUP_FOLDER               1081
#define IDC_DEFAULT                     1082
#define IDC_PROGRESS                    1086
#define IDC_DELETE                      1088
#define IDC_PROGRESS1                   1089
#define IDC_LIBRARY_FOLDER              1090
#define IDC_LIBRARY_REFERENCE           1092
#define IDC_EXTERNAL                    1093
#define IDC_INBOX_REFERENCE             1093
#define IDC_LIBRARY_LIST                1094
#define IDC_SEPARATOR                   1095
#define IDC_BACKUP_REFERENCE            1096
#define IDC_BACKUP_LIST                 1096
#define IDC_TITLE_ONLY                  1097
#define IDC_KEYWORD_REFERENCE           1097
#define IDC_TITLE_CODE                  1098
#define IDC_AUTO_ROTATION               1099
#define IDC_APP_LIST                    1100
#define IDC_APP_NAME                    1101
#define IDC_APP_FILE                    1102
#define IDC_CLOSE                       1104
#define IDC_RIGHT_ROTATE                1105
#define IDC_LEFT_ROTATE                 1106
#define IDC_SMALL_NORMAL                1106
#define IDC_REVERSE                     1107
#define IDC_SMALL_HISPD                 1107
#define IDC_SMALL_HIRES                 1108
#define IDC_RADIO1                      1109
#define IDC_PASSWORD                    1109
#define IDC_RADIO2                      1110
#define IDC_PASSWORD2                   1110
#define IDC_RADIO3                      1111
#define IDC_COPYRIGHT                   1111
#define IDC_RADIO4                      1112
#define IDC_PRODUCT                     1112
#define IDC_LIBLIST                     1114
#define IDC_UPDATE_INFO                 1115
#define IDC_TEXT_DATA                   1117
#define IDC_TEXT                        1120
#define IDC_COPY_DATA                   1121
#define IDC_INBOX_FOLDER                1122
#define IDC_KEYWORD_FOLDER              1123
#define IDC_ICON_NONE                   1125
#define IDC_ICON_SMALL                  1126
#define IDC_ICON_LARGE                  1127
#define IDC_PICT_BMP                    1128
#define IDC_PICT_GIF                    1129
#define IDC_PICT_JPG                    1130
#define IDC_PICT_PNG                    1131
#define IDC_ALL_SELECT                  1138
#define IDC_ATT_HLIMIT                  1140
#define IDC_ATT_VLIMIT                  1141
#define IDC_ATT_HPIXEL                  1142
#define IDC_ATT_VPIXEL                  1143
#define IDC_ATT_SCALE                   1144
#define IDC_ATT_ACTUAL                  1145
#define IDC_ATT_REDUCTION               1146
#define IDC_IMAGE_EDITOR                1147
#define IDC_SELECT_FILE                 1148
#define IDC_IMAGE_EDITOR_ICON           1149
#define IDC_EDIT_DBLCLICK               1150
#define IDC_PICT_CLIPBOARD              1151
#define IDC_PICT_WINDOW                 1152
#define IDC_SEARCH_TEXT                 1153
#define IDC_FIND_EXPERT                 1154
#define IDC_PRODUCT_URL                 1343
#define IDC_COMPANY_URL                 1344
#define IDC_EMAIL_ADDR                  1345
#define IDS_SELECT_LIBRARY              3001
#define IDS_BACKUP_NORMAL               3002
#define IDS_BACKUP_FAIL                 3003
#define IDS_SELECT_DELETE_LIBRARY       3004
#define IDS_DELETE_SELECTED_LIBRARY     3005
#define IDS_READ_NOTIFY                 3006
#define IDS_READ_PICT_FILE_FAIL         3007
#define IDS_ONLY_COMPRESS               3008
#define IDS_VALID_COLOR                 3009
#define IDS_INPUT_DATA_SAVE             3010
#define IDS_UPDATE_DATA_SAVE            3011
#define IDS_INPUT_KEYWORD               3012
#define IDS_FIND_ERROR                  3013
#define IDS_NO_KEYWORD_INDEX            3014
#define IDS_OLD_KEYWORD_INDEX           3015
#define IDS_SELECT_FOLDER_TYPE          3016
#define IDS_CREATE_INBOX_FAIL           3017
#define IDS_INPUT_SERVER_NAME           3018
#define IDS_REDUCTION_RATIO             3019
#define IDS_CREAE_KEYWORD_INDEX_FAIL    3020
#define IDS_CREATE_KEYWORD_INDEX_ERROR  3021
#define IDS_CREATE_KEYWORD_INDEX_NORMAL 3022
#define IDS_NOT_FOUND_YMUPDATE_DLL      3023
#define IDS_ONLINE_UPDATE_FAIL          3024
#define IDS_CREATE_CACHE_FOLDER_FAIL    3025
#define IDS_OLD_DATABASE_VERSION        3026
#define IDS_PROGRAM_ERROR               3027
#define IDS_LIBRARY_ALREADY_OPEN        3028
#define IDS_ACCESS_DENY                 3029
#define IDS_PASSWORD_INCORRECT          3030
#define IDS_DELETE_SELECT               3031
#define IDS_DELETE_LIBRARY_FAIL         3032
#define IDS_OFFLINE_FOLDER_UPDATE       3033
#define IDS_OFFLINE_DATA_UPDATE         3034
#define IDS_READ_CACHE                  3035
#define IDS_DELETE_CACHE                3036
#define IDS_SEND_DATA_FOLDER            3037
#define IDS_SELECT_DATA_FOLDER          3038
#define IDS_FILE_PACK                   3039
#define IDS_FILE_PACK_END               3040
#define IDS_SELECT_EXPORT               3041
#define IDS_EXPORT_DATA_FOLDER          3042
#define IDS_SELECT_IMPORT_FOLDER        3043
#define IDS_PICT_FILE_IMPORT            3044
#define IDS_SELECT_TRANSFER_DATA        3045
#define IDS_STANSFER_DATA               3046
#define IDS_PRINT_FOLDER                3047
#define IDS_SELECT_PRINT_DATA           3048
#define IDS_OFFLINE_MODE                3049
#define IDS_DATA_NOT_FOUND              3050
#define IDS_PASSWORD_UNMATCH            3051
#define IDS_SELECT_ROTATION             3052
#define IDS_NOT_FOUND_LIBRARY           3053
#define IDS_CONxxxT_SERVER_FAIL         3054
#define IDS_SELECT_RECTORE_LIBRARY      3055
#define IDS_RESTORE_LIBRARY             3056
#define IDS_RESTORE_FAIL                3057
#define IDS_RESTORE_NORMAL              3058
#define IDS_INPUT_APPLICATION_NAME      3059
#define IDS_INPUT_EXECUTABLE_FILE       3060
#define IDS_SELECT_DELETE_ITEM          3061
#define IDS_DELETE_SELECT_ITEM          3062
#define IDS_NO_IMAGE_DATA               3063
#define IDS_CLOSE                       4001
#define IDS_CANCEL                      4002
#define IDS_LIBRARY_NAME                5001
#define IDS_BACKUP_TIME                 5002
#define IDS_NO_TITLE                    5003
#define IDS_NO_ROTATION                 5004
#define IDS_RIGHT_ROTATION              5005
#define IDS_HALF_ROTATION               5006
#define IDS_LEFT_ROTATION               5007
#define IDS_UNKNOWN                     5008
#define IDS_PICTURE_FILE                5009
#define IDS_SELECT_PICT_FILE_MULTI      5010
#define IDS_SELECT_PICT_FILE            5011
#define IDS_FIND_FOLDER                 5012
#define IDS_CONDITION                   5013
#define IDS_KEYWORD                     5014
#define IDS_KEYWORD_FIND                5015
#define IDS_FIND                        5016
#define IDS_NAME                        5017
#define IDS_LIBRARY                     5018
#define IDS_CREATOR                     5019
#define IDS_REMARK                      5020
#define IDS_CREATE_DATE                 5021
#define IDS_FIND_RESULT                 5022
#define IDS_INBOX                       5023
#define IDS_MMLIB_FOLDER                5024
#define IDS_NEW_DOCUMENT                5025
#define IDS_OPEN                        5026
#define IDS_NEW_DATA                    5027
#define IDS_PRINT                       5028
#define IDS_PREVIEW                     5029
#define IDS_SEND                        5030
#define IDS_CUT                         5031
#define IDS_COPY                        5032
#define IDS_PASTE                       5033
#define IDS_KEYWORD2                    5034
#define IDS_RETURN                      5035
#define IDS_HELP                        5036
#define IDS_PREV_DATA                   5037
#define IDS_NEXT_DATA                   5038
#define IDS_FULL_VIEW                   5039
#define IDS_REDUCTION_PICT              5040
#define IDS_LIST_VIEW                   5041
#define IDS_DETAIL_VIEW                 5042
#define IDS_SCALE                       5043
#define IDS_AUTO_SIZE                   5044
#define IDS_AUTO_WIDTH                  5045
#define IDS_ENLARGE                     5046
#define IDS_REDUCTION                   5047
#define IDS_ALL_ROTATION                5048
#define IDS_OTHER_WINDOW                5049
#define IDS_DEFAULT_FONT                5050
#define IDS_NEW_DATA2                   5051
#define IDS_LIBRARY_UPDATE              5052
#define IDS_FOLDER_UPDATE               5053
#define IDS_DATA_UPDATE                 5054
#define IDS_FOLDER                      5055
#define IDS_DATA                        5056
#define IDS_EXPORT_FILE                 5057
#define IDS_MML_FILE                    5058
#define IDS_PRESTO_PAGEMANAGER_FOLDER   5059
#define IDS_IMPORT_FOLDER               5060
#define IDS_IMPORT_FILE                 5061
#define IDS_MULTIMEDIA_LIBRARY          5062
#define IDS_CODE                        5063
#define IDS_UPDATE_DATE                 5064
#define IDS_SERVER_NAME                 5065
#define IDS_DIRECTORY                   5066
#define IDS_SELECT_LIBRARY_FOLDER       5067
#define IDS_SELECT_CACHE_FOLDER         5068
#define IDS_SELECT_BACKUP_FOLDER        5069
#define IDS_SELECT_INBOX_FOLDER         5070
#define IDS_SELECT_KEYWORD_FOLDER       5071
#define IDS_APPLICATION_NAME            5072
#define IDS_EXECUTABLE_FILE             5073
#define IDS_PROGRAM                     5074
#define IDS_ALL_FILES                   5075
#define IDS_SELECT_TRANSFER_APPL        5076
#define IDS_SET_ENVIRONMENT             5077
#define IDS_NO_TITLE_1                  5078
#define IDS_STRING5079                  5079
#define IDS_LEFT_ROTATION2              5080
#define IDS_RIGHT_ROTATION2             5081
#define IDS_HELP_URL                    5082
#define IDS_ONLINE_UPDATE               5083
#define IDS_FIRST_DATA                  5084
#define IDM_FOLDER_NEW                  32773
#define IDM_FOLDER_OPEN                 32774
#define IDM_LIB_NEW                     32775
#define IDM_LIB_OPEN                    32776
#define IDM_LIB_CLOSE                   32777
#define IDM_LIB_RENAME                  32778
#define IDM_FOLDER_RENAME               32779
#define IDM_VIEW_ICON                   32780
#define IDM_VIEW_LIST                   32781
#define IDM_VIEW_DETAIL                 32782
#define IDM_VIEW_PICT                   32783
#define IDM_PICT_CAMERA                 32784
#define IDM_PICT_SCANNER                32785
#define IDM_PICT_FILE                   32786
#define IDM_FILE_DELETE                 32789
#define IDM_RELOAD                      32791
#define IDM_PICT_OPEN                   32792
#define IDM_VIEW_RELOAD                 32793
#define IDM_PICT_RIGHT_ROTATE           32804
#define IDM_PICT_LEFT_ROTATE            32805
#define IDM_PICT_AUTOSIZE               32826
#define IDM_PICT_ENLARGE                32827
#define IDM_PICT_REDUCE                 32828
#define IDM_DETAIL_NAME                 32831
#define IDM_DETAIL_CREATOR              32832
#define IDM_DETAIL_CDATE                32833
#define IDM_DETAIL_UDATE                32834
#define IDM_DETAIL_CODE                 32835
#define IDM_DETAIL_REMARK               32836
#define IDM_DETAIL_KEYWORD              32837
#define IDM_DETAIL_SERVER               32838
#define IDM_DETAIL_DIRECTORY            32839
#define IDM_VIEW_UP                     32843
#define IDM_VIEW_UPFOLDER               32845
#define IDM_FIND                        32848
#define IDM_PROPERTY                    32849
#define ID_CACHE_READ                   32851
#define ID_CACHE_CLEAR                  32852
#define IDM_OPTION                      32853
#define IDW_COMBO                       32858
#define IDM_PICT_AUTOSIZE2              32859
#define IDM_REFIND                      32864
#define IDM_PACK                        32865
#define IDM_FILE_PACK                   32866
#define IDM_TOOLBAR_STANDARD            32867
#define IDM_TOOLBAR_PICT                32868
#define IDM_TOOLBAR_STRING              32869
#define ID_FILE_EXPORT                  32870
#define ID_FILE_IMPORT                  32871
#define IDM_BACKUP                      32872
#define IDM_RESTORE                     32873
#define IDM_ONLINE_UPDATE               32874
#define IDM_ONLINE_MANUAL               32875
#define IDM_TRANS_REG                   32876
#define IDM_IMPORT_MML                  32878
#define IDM_IMPORT_PPM                  32879
#define ID_IMPORT_BMP                   32880
#define IDM_IMPORT_BMP                  32881
#define IDM_PICT_ALL_ROTATE             32884
#define IDM_PICT_WINDOW                 32885
#define IDM_FILE_PASSWORD               32897
#define IDM_FILE_PERMISSION             32898
#define IDM_FONT                        32899
#define IDM_CLOSE_PICT                  32900
#define IDM_CLOSE_TEXT                  32901
#define IDM_VIEW_PREV                   32902
#define IDM_VIEW_NEXT                   32903
#define ID_NEW_DATA                     32904
#define IDM_TOOLBAR_VIEW                32906
#define IDM_VIEW_MAX                    32907
#define IDM_KEYWORD                     32910
#define IDM_CLOSE_FIND                  32911
#define IDM_MAKE_INDEX                  32913
#define IDC_FIND                        32914
#define IDM_EDIT_IMAGE                  32915
#define IDM_DETAIL_FIRSTDATA            32918
#define ID_INDICATOR_INFO               59143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         32919
#define _APS_NEXT_CONTROL_VALUE         1157
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
