//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PcVideo.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_CONxxxT                     101
#define IDM_EXIT                        101
#define IDR_CHAT                        101
#define IDD_SETTING                     102
#define IDM_CONxxxT                     102
#define IDD_CAMERA                      103
#define IDM_DISCONxxxT                  103
#define IDM_SETTING                     104
#define IDM_TILE                        106
#define IDD_LOGFILE                     107
#define IDM_FRONT                       107
#define IDD_SETHOST                     108
#define IDM_CHAT                        110
#define IDM_FONT                        113
#define IDM_LOGFILE                     114
#define IDM_IPADDRESS                   116
#define IDM_VIDEO_SOURCE                117
#define IDM_SETHOST                     119
#define IDM_CHATCALL                    120
#define IDM_VOICE                       121
#define IDD_VERSION                     122
#define IDD_LICENSE                     123
#define IDM_REMOTE_SETTING              123
#define IDC_MOVE                        124
#define IDD_CAMERA_OPTION               124
#define IDM_VERSION                     124
#define IDB_NONE                        125
#define IDD_REMOTE                      125
#define IDB_CHAT                        126
#define IDB_VOICE                       127
#define IDD_CALL                        127
#define IDR_MAINFRAME                   128
#define IDD_ANSWER                      128
#define IDB_REFLECT                     129
#define IDB_VIDEO_MASK                  132
#define IDB_CHAT_MASK                   133
#define IDB_NONE_MASK                   134
#define IDB_REFLECT_MASK                135
#define IDB_VOICE_MASK                  136
#define IDD_CAMERA_PRESET               137
#define IDB_DLL                         138
#define IDB_DLL_MASK                    139
#define IDB_VIDEO                       140
#define IDI_MICROPHONE                  141
#define IDI_ICON3                       142
#define IDI_ICON4                       143
#define IDI_ICON5                       144
#define IDI_ICON6                       145
#define IDD_VOICE                       148
#define IDI_SPEAKER                     149
#define IDD_LOGIN                       149
#define IDI_CHAT                        151
#define IDM_CONxxxT_DIRECT              200
#define IDC_OPENHAND                    268
#define IDC_CLOSEHAND                   269
#define IDC_HMOVE                       270
#define IDC_VMOVE                       271
#define IDC_USERID                      1000
#define IDC_HOSTNAME                    1001
#define IDS_CAMERA_LOCKED               1001
#define IDC_PASSWORD                    1001
#define IDS_CAMERA_DENY                 1002
#define IDC_VIDEO_CAPTURE               1002
#define IDC_SAVE_PASSWORD               1002
#define IDC_RECEIVEVIDEO                1003
#define IDS_CAMERA_NOCONTROL            1003
#define IDC_CHANNEL_NO                  1004
#define IDC_USERNAME                    1004
#define ID_VOICECALL                    1004
#define IDS_CAMERA_INIT                 1004
#define IDC_SERVER_NAME                 1004
#define IDS_CAMERA_BUSY                 1005
#define IDC_MOVIESIZE                   1006
#define IDS_CAMERA_READY                1006
#define IDC_INPUT_VOLUME                1006
#define IDC_STILLSIZE                   1007
#define IDS_CAMERA_FOCUS                1007
#define IDC_OUTPUT_VOLUME               1007
#define IDC_RECVSIZE                    1008
#define IDS_CAMERA_NOSUPPORT            1008
#define IDC_SEND                        1008
#define IDS_CAMERA_NORESPONSE           1009
#define IDC_SENDER_LIST                 1009
#define IDC_MAXBPS                      1010
#define IDC_FULL_DUPLEX_MODE            1010
#define IDC_MAXSPEED                    1011
#define IDC_AUTO_SEND_LEVEL             1011
#define IDC_LOGFILE                     1012
#define IDC_INPUT_LEVEL                 1012
#define IDC_CAMERA_TELE                 1013
#define IDC_REPLACE                     1013
#define IDC_OUTPUT_LEVEL                1013
#define IDC_CAMERA_WIDE                 1014
#define IDC_APPEND                      1014
#define IDC_MANUAL_MODE                 1014
#define IDC_CAMERA_HOME                 1015
#define IDC_ALWAYSLOG                   1015
#define IDC_AUTO_MODE                   1015
#define IDC_CAMERA_UP                   1016
#define IDC_FIXED_MODE                  1016
#define IDC_CAMERA_DOWN                 1017
#define IDC_REFERENCE                   1017
#define IDC_MIC_ICON                    1017
#define IDC_CAMERA_LEFT                 1018
#define IDC_HOSTLIST                    1018
#define IDC_SPEAKER_ICON                1018
#define IDC_CAMERA_RIGHT                1019
#define IDC_NAME                        1019
#define IDC_SWITCH                      1019
#define IDC_AUTO_SEND_LEVEL2            1020
#define IDC_CHANNELNO                   1021
#define IDC_INPUT_DEVICE                1021
#define IDC_CAMERA_OPTION               1022
#define IDC_DELETE                      1022
#define IDC_AUTO_LEVEL_CONTROL          1022
#define IDC_CAMERA_STATUS               1024
#define IDC_VOICE_INPUT_DEVICE          1024
#define IDC_VOICE_OUTPUT_DEVICE         1025
#define IDC_CHANGE                      1026
#define IDC_VOICE_BUFFER_NUM            1026
#define IDC_CAMERA_PS1                  1027
#define IDC_VIDEOQUALITY_SPIN           1027
#define IDC_CAMERA_PS2                  1028
#define IDC_EDGEENHANCE_SPIN            1028
#define IDC_CAMERA_PS3                  1029
#define IDC_MAXBPS_SPIN                 1029
#define IDC_CAMERA_PS4                  1030
#define IDC_VOICE_BUFFER_NUM_SPIN       1030
#define IDC_CAMERA_PS5                  1031
#define IDC_CAMERA_PS6                  1032
#define IDC_CAMERA_AUTO                 1033
#define IDC_CAMERA_MANUAL               1034
#define IDC_CALLMES                     1034
#define IDC_CAMERA_FAR                  1035
#define IDC_VIDEOCOLORS                 1035
#define IDC_ANSMES                      1035
#define IDC_ANSMES3                     1036
#define IDC_CAMERA_NEAR                 1036
#define IDC_VIDEOQUALITY                1036
#define IDC_CAMERA_COMMENT              1037
#define IDC_RESIZE                      1037
#define IDC_CAMERA_PS7                  1038
#define IDC_DISPINFO                    1038
#define IDC_CAMERA_PS8                  1039
#define IDC_FIXEDSIZE                   1039
#define IDC_CAMERA_PRESET               1040
#define IDC_SENDINFO                    1040
#define IDC_CAMERA_PAN                  1041
#define IDC_FIXEDASPECT                 1041
#define IDC_CAMERA_TILT                 1042
#define IDC_REMOTESETTING               1042
#define IDC_EDGEENHANCE                 1043
#define IDC_CAMERA_TYPE                 1044
#define IDC_CAMERA_LIGHTADJUST          1045
#define IDC_CAMERA_AUTOWHITE            1046
#define IDC_CAMERACHANGE                1046
#define IDC_CAMERA_SHUTTER_60           1047
#define IDC_FULLFRAME                   1047
#define IDC_CAMERA_SHUTTER_100          1048
#define IDC_REGISTNO                    1048
#define IDC_LICENSE                     1049
#define IDC_CAMERA_PORT                 1050
#define IDC_CAMERA_PANSPEED             1051
#define IDC_VERSION                     1051
#define IDC_CAMERA_TILTSPEED            1052
#define IDC_REMOTE_CHAT                 1052
#define IDC_CAMERA_ZOOMLOW              1053
#define IDC_REMOTE_VOICE                1053
#define IDC_CAMERA_ZOOMHIGH             1054
#define IDC_REMOTE_RESTART              1054
#define IDC_CAMERA_SHUTTER_AUTO         1055
#define IDC_REMOTE_EXIT                 1055
#define IDC_CAMERA_PANPPS               1056
#define IDC_REMOTE_SVOICE               1056
#define IDC_CAMERA_TILTPPS              1057
#define IDC_REMOTE_EXEC                 1057
#define IDC_CAMERA_WIDECONVERTER        1058
#define IDC_REMOTE_DOWNLOAD             1058
#define IDC_CAMERA_PRESETNO             1063
#define IDC_CAMERA_LOCK                 1065
#define IDC_REMOTE_COMMAND              1066
#define IDC_REMOTE_DOWNLOAD_FILE        1067
#define IDS_CALLING                     2000
#define IDS_CHAT_CALL                   2001
#define IDS_VOICE_CALL                  2002
#define IDS_SEL_CALL                    2003
#define IDS_RESPONSE                    2004
#define IDS_NO_RESPONSE                 2005
#define IDS_NO_CHAT                     2006
#define IDS_NO_VOICE                    2007
#define IDS_ON_CHAT                     2008
#define IDS_ON_VOICE                    2009
#define IDS_INPUT_COMMENT               2010
#define IDS_IMAGE_SIZE                  2011
#define IDS_NO_HOSTNAME                 2012
#define IDS_LISENCE_LIMIT               2013
#define IDS_NO_YMUPDATE                 2014
#define IDS_NO_ONLINEUPDATE             2015
#define IDS_CONxxxT                     2016
#define IDS_DISCONxxxT                  2017
#define IDS_VIDEO                       2018
#define IDS_CHAT                        2019
#define IDS_VOICE                       2020
#define IDS_ALIGN                       2021
#define IDS_MENU_CONxxxT                2022
#define IDS_MENU_DISCONxxxT             2023
#define IDS_OTHER_HOST                  2024
#define IDS_SETTING                     2025
#define IDS_REMOTE_SETTING              2026
#define IDS_NO_REMOTE                   2027
#define IDS_NO_PCVIDEO                  2028
#define IDS_RECV_MESSAGE                2029
#define IDS_END_PCVIDEO                 2030
#define IDS_NO_PCVSTART                 2031
#define IDS_PCVIDEO_RESTART             2032
#define IDS_NO_FILE                     2033
#define IDS_DOWNLOAD                    2034
#define IDS_COLOR_MONO                  2035
#define IDS_COLOR_HIGH                  2036
#define IDS_COLOR_TRUE                  2037
#define IDS_OTHER                       2038
#define IDS_CANNON_VCC1                 2039
#define IDS_ERR_WINSOCK                 2040
#define IDS_ERR_LOCALHOST               2041
#define IDS_ERR_LOCAL_IP                2042
#define IDS_ERR_UDP                     2043
#define IDS_ERR_BIND                    2044
#define IDS_ERR_TCP                     2045
#define IDS_ERR_LISTEN                  2046
#define IDS_DENY_CONxxxT                2047
#define IDS_UNDEFINED_ERR               2048
#define IDS_CAMERA_CONTROL              2049
#define IDS_CAMERA_CONTROL2             2050
#define IDS_UNDEFINED_MSG               2051
#define IDS_CHAT_FILE                   2052
#define IDS_SAVE_CHAT                   2053
#define IDS_REF_LOGFILE                 2054
#define IDS_STILL_IMAGE                 2055
#define IDS_REG_LIMIT                   2056
#define IDS_SENDING                     2057
#define IDS_SEND                        2058
#define IDS_SWITCH_SEND                 2059
#define IDS_SWITCH_RECV                 2060
#define IDS_ONLINE_UPDATE               2061
#define IDS_STRING3000                  3000
#define IDS_STRING3001                  3001
#define IDS_STRING3002                  3002
#define IDS_STRING3003                  3003
#define IDS_STRING3004                  3004
#define IDS_STRING3005                  3005
#define IDS_STRING3006                  3006
#define IDS_STRING3007                  3007
#define IDS_STRING3008                  3008
#define IDS_STRING3009                  3009
#define IDS_STRING3010                  3010
#define IDS_STRING3011                  3011
#define IDS_STRING3012                  3012
#define IDS_STRING3013                  3013
#define IDS_STRING3014                  3014
#define IDS_STRING3015                  3015
#define IDI_MICROPHONE_OFF              31235
#define IDI_SPEAKER_OFF                 31236
#define IDI_VIDEO                       31237
#define IDM_ORDER_CONxxxT               32771
#define IDM_ORDER_NAME                  32772
#define IDM_ORDER_IPADDRESS             32773
#define IDM_SEND_CAMERA                 32774
#define IDM_RECV_CAMERA                 32775
#define IDM_SEND_DISP                   32776
#define IDM_RECV_DISP                   32777
#define IDM_SEND_STILL                  32778
#define IDM_RECV_STILL                  32779
#define ID_ON_HELP                      32780
#define IDM_HELP_KEY                    32781
#define IDM_HELP_CONTENTS               32782
#define IDM_VIDEO_FORMAT                32783
#define IDM_ONLINE_UPDATE               32786
#define IDS_INDICATOR_FPS               59143
#define IDS_INDICATOR_BPF               59144
#define IDS_INDICATOR_BPS               59145
#define IDS_INDICATOR_COMPRATE          59146
#define IDS_INDICATOR_VIDEO             59147
#define IDS_INDICATOR_CHAT              59148
#define IDS_INDICATOR_VOICE             59149

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1036
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
