<?php

//  1.全般問合せ受付用　　info
//     どこに問い合わせたら良いかわからないものすべての窓口
$mailaddr_1 = "info@melonpan.net";

//  2.発行者向け受付用　　office
//　　発行者との事務的連絡、問合せ窓口
$mailaddr_2 = "office@melonpan.net";

//  3.システム関係受付用　　sys
//　　サーバトラブル等、システム上の障害に関する問合せ窓口
$mailaddr_3 = "sys@melonpan.net";

//  4.読者向け受付用　　staff
//　　メルマガの内容や購読・解除の仕方等の問合せ窓口
$mailaddr_4 = "staff@melonpan.net";

//  5.広告主向け受付用　　ad
//　　りばっチャやバナー、めろんぱんレターへの広告出稿に関する問合せ窓口
$mailaddr_5 = "ad@melonpan.net";

//  6.パスワード自動通知用　　pass
$mailaddr_6 = "pass@melonpan.net";

//  7.メロンパ登録確認メール送信用　　welcome
$mailaddr_7 = "welcome@melonpan.net";

//  8.創刊手続き完了メール送信用　　ichiro
$mailaddr_8 = "ichiro@melonpan.net";

//  9.発行仮登録完了メール送信用　　jiro
$mailaddr_9 = "jiro@melonpan.net";

//10.発行本登録完了メール送信用　　saburo
$mailaddr_10 = "saburo@melonpan.net";

//11.『めろんぱんニュース』(仮称）送信用　　mpan-news
//     発行者向けニュース、
$mailaddr_11 = "mpan-news@melonpan.net";

//12.メルマガ発信用　　magazine
//　　めろんぱんで発行されるメルマガのfromアドレスに使うアドレス
//　　reply-toには、メルマガごとに発行者が設定したアドレス
$mailaddr_12 = "magazine@melonpan.net";

//13.『めろんぱんレター』送信用　　letter
//　　めろんぱんレターは、「めろんぱんで発行されるメルマガのひとつ」という
//　　位置づけですので、fromはmagazine@melonpan.netとなり、そのreply-toが
//　　letter@melonpan.netになる、ということです。
$mailaddr_13 = "letter@melonpan.net";

//
//------------------------------------------------------------------------
//14.バ・キューン発行用　　ba-qn@xxxxxxx.co.jp
//　　「バ・キューン」はめろんぱんが発行するのではなく、○○○○○○が
//　　発行する新聞なので、@xxxxxxx.co.jpとなります。
$mailaddr_14 = "ba-qn@xxxxxxx.co.jp";

//また今日追加ということでもう一つお願いいたします。
//15.イエローカード・レッドカード送信用　　check
$mailaddr_15 = "check@melonpan.net";

?>
